import React,{useEffect,useState} from 'react'
import QRCode from 'qrcode'
import {BarChart3,BellRing,ClipboardList,ExternalLink,Link2,Plus,Settings2,UserRound} from 'lucide-react'
import {useAuth} from '../contexts/AuthContext'
import {supabase} from '../lib/supabase'
import {insertRow,nextId,updateRow} from '../services/api'
import {formatDateTime,initials,money,num} from '../utils/format'
import SearchFilterBar from '../components/SearchFilterBar'
import DataTable from '../components/DataTable'
import StatusBadge from '../components/StatusBadge'
import NoticeRenderer,{NoticeItem} from '../components/NoticeRenderer'
import Modal from '../components/Modal'
import EmptyState from '../components/EmptyState'
import {Field,FormNote,FormSection,SwitchField} from '../components/FormKit'
import {DateStack,IdentityCell,RouteCell,RowActions} from '../components/TableKit'

const formDefaults={show_goods:true,show_vehicle:true,show_schedule:true,show_notes:false,require_goods:false,require_vehicle:false}

export default function AgentPortal(){
 const {profile,logout,refreshProfile}=useAuth()
 const [tab,setTab]=useState('dashboard'),[leads,setLeads]=useState([]),[form,setForm]=useState(null),[notices,setNotices]=useState([]),[types,setTypes]=useState([]),[profileNotes,setProfileNotes]=useState([]),[partner,setPartner]=useState(null),[events,setEvents]=useState([])
 const [search,setSearch]=useState(''),[status,setStatus]=useState('All'),[sort,setSort]=useState('newest'),[view,setView]=useState('table'),[add,setAdd]=useState(false),[leadEdit,setLeadEdit]=useState(null),[noticeEdit,setNoticeEdit]=useState(null),[qr,setQr]=useState('')
 const load=async()=>{
  if(!profile)return
  const queries=[
   supabase.from('leads').select('*').eq('created_by_profile_id',profile.id).eq('archived',false).order('created_at',{ascending:false}),
   supabase.from('public_forms').select('*').eq('owner_profile_id',profile.id).maybeSingle(),
   supabase.from('notices').select('*').eq('archived',false).order('created_at',{ascending:false}),
   supabase.from('vehicle_types').select('*').eq('active',true).eq('archived',false).order('sort_order'),
   supabase.from('profile_notes').select('*').eq('profile_type','agent').eq('record_id',profile.id).order('created_at',{ascending:false}),
   supabase.from('lead_events').select('*').eq('actor_profile_id',profile.id).order('created_at',{ascending:false}).limit(50)
  ]
  if(profile.linked_entity_type==='referral_partner'&&profile.linked_entity_id)queries.push(supabase.from('referral_partners').select('*').eq('id',profile.linked_entity_id).maybeSingle())
  const res=await Promise.all(queries)
  setLeads(res[0].data||[]);setForm(res[1].data||null);setNotices(res[2].data||[]);setTypes(res[3].data||[]);setProfileNotes(res[4].data||[]);setEvents(res[5].data||[]);setPartner(res[6]?.data||null)
  if(res[1].data)QRCode.toDataURL(`${location.origin}/public/${res[1].data.token}`,{width:260,margin:1}).then(setQr)
  else setQr('')
 }
 useEffect(()=>{load();if(!profile)return;const c=supabase.channel(`portal:${profile.id}`).on('postgres_changes',{event:'*',schema:'public',table:'leads',filter:`created_by_profile_id=eq.${profile.id}`},load).on('postgres_changes',{event:'*',schema:'public',table:'public_forms',filter:`owner_profile_id=eq.${profile.id}`},load).on('postgres_changes',{event:'*',schema:'public',table:'notices'},load).subscribe();return()=>supabase.removeChannel(c)},[profile?.id])
 if(!profile)return null
 const filtered=[...leads.filter(l=>(status==='All'||l.status===status)&&(!search||[l.id,l.name,l.phone,l.pickup,l.drop,l.vehicle_type].join(' ').toLowerCase().includes(search.toLowerCase())))].sort((a,b)=>sort==='oldest'?String(a.created_at||'').localeCompare(String(b.created_at||'')):sort==='name'?String(a.name||'').localeCompare(String(b.name||'')):String(b.created_at||'').localeCompare(String(a.created_at||'')))
 const converted=leads.filter(l=>l.status==='Converted').length,confirmed=leads.filter(l=>['Confirmed','Converted'].includes(l.status)).length
 const adminNotices=notices.filter(n=>n.owner_type!=='Agent'&&Array.isArray(n.targets)&&n.targets.includes('Agent Dashboard'))
 const ownFormNotices=notices.filter(n=>n.owner_type==='Agent'&&n.owner_profile_id===profile.id&&Array.isArray(n.targets)&&n.targets.includes('Agent Public Form'))
 return <div className="agent-shell v25-portal-shell">
  <header className="agent-top"><div className="agent-brand"><div className="agent-brand-logo">🛺</div><div><b>RikshaMS</b><small>Referral Portal</small></div></div><div className="agent-user-mini"><div className="avatar">{initials(profile.display_name)}</div><div><b>{profile.display_name}</b><small>{profile.profile_type||profile.role}</small></div><button className="outline small" onClick={logout}>Logout</button></div></header>
  <main className="agent-main">
   <section className="agent-hero v25-agent-hero"><div className="agent-hero-copy"><small>{profile.profile_type||'Portal User'}</small><h1>{profile.display_name}</h1><span>Manage your leads, public enquiry link, notices and profile from one workspace.</span><div className="agent-hero-meta"><span>ID {profile.profile_id||'—'}</span><span>{form?.active?'Public Form Live':'Public Form Off'}</span>{partner?.referral_code&&<span>Code {partner.referral_code}</span>}</div></div>{qr&&<div className="hero-qr-wrap"><img className="agent-qr" src={qr}/><small>Public Form QR</small></div>}</section>
   <nav className="agent-nav v25-agent-nav">{[['dashboard',<BarChart3 size={16}/>,'Dashboard'],['leads',<ClipboardList size={16}/>,'My Leads'],['public',<ExternalLink size={16}/>,'Public Form'],['notices',<BellRing size={16}/>,'Notices'],['profile',<UserRound size={16}/>,'My Profile']].map(([k,i,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{i} {l}</button>)}</nav>

   {tab==='dashboard'&&<><div className="agent-stats v25-agent-stats"><div><small>My Leads</small><strong>{leads.length}</strong><span>Total attributed enquiries</span></div><div><small>Confirmed</small><strong>{confirmed}</strong><span>Customer-ready leads</span></div><div><small>Converted</small><strong>{converted}</strong><span>{leads.length?Math.round(converted/leads.length*100):0}% conversion</span></div><div><small>Public Form</small><strong>{form?.active?'Live':'Off'}</strong><span>{form?'Ready to share':'Create your form'}</span></div></div><div className="v10-dashboard-actions"><button className="primary" onClick={()=>setAdd(true)}><Plus size={16}/> Add Lead</button><button className="outline" onClick={()=>setTab('leads')}>Manage Leads</button><button className="outline" onClick={()=>setTab('public')}><Link2 size={16}/> Public Form & QR</button></div><div className="agent-grid"><section className="agent-section"><div className="agent-section-head"><div><h3>Recent Leads</h3><small>Your latest enquiries</small></div></div><AgentLeadTable rows={leads.slice(0,6)} onOpen={setLeadEdit}/></section><section className="agent-section"><div className="agent-section-head"><div><h3>Admin Notices</h3><small>Updates shared with portal users</small></div></div><NoticeRenderer notices={adminNotices}/>{!adminNotices.length&&<EmptyState title="No active notices"/>}</section></div></>}

   {tab==='leads'&&<section className="agent-section"><div className="agent-section-head"><div><h3>My Leads</h3><small>Add, search, filter and update the leads attributed to you.</small></div><button className="primary" onClick={()=>setAdd(true)}><Plus size={16}/> Add Lead</button></div><SearchFilterBar search={search} onSearch={setSearch} view={view} onView={setView} placeholder="Search lead, customer, phone or route…" className="pro-module-toolbar" onReset={()=>{setSearch('');setStatus('All');setSort('newest')}}><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{Array.from(new Set(leads.map(x=>x.status).filter(Boolean))).map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="name">Name A–Z</option></select></SearchFilterBar>{view==='table'?<AgentLeadTable rows={filtered} onOpen={setLeadEdit}/>:<div className="agent-lead-cards">{filtered.map(l=><article className="agent-lead-card clickable" key={l.id} onClick={()=>setLeadEdit(l)}><div className="list-card-head"><b>{l.id}</b><StatusBadge status={l.status}/></div><h4>{l.name}</h4><small>{l.phone}</small><div className="agent-lead-route">{l.pickup} → {l.drop}</div><div className="agent-lead-meta"><span>{l.vehicle_type||'Vehicle TBD'}</span><span>{formatDateTime(l.created_at)}</span></div></article>)}</div>}</section>}

   {tab==='public'&&<AgentPublicForm form={form} profile={profile} qr={qr} notices={ownFormNotices} onReload={load} onNewNotice={()=>setNoticeEdit({})} onEditNotice={n=>setNoticeEdit(n)}/>} 
   {tab==='notices'&&<section className="agent-section"><div className="agent-section-head"><div><h3>Notices</h3><small>Admin notices for your dashboard and notices you publish to your own public form.</small></div><span className="chip">{adminNotices.length+ownFormNotices.length}</span></div><h4 className="section-mini-title">From Admin</h4><NoticeRenderer notices={adminNotices}/><h4 className="section-mini-title mt">My Public Form Notices</h4><div className="notice-library">{ownFormNotices.map(n=><article className="notice-admin-card" key={n.id}><NoticeItem notice={n}/><div className="table-actions"><button className="outline small" onClick={()=>setNoticeEdit(n)}>Edit</button><button className="ghost small" onClick={async()=>{await updateRow('notices',n.id,{active:!n.active});load()}}>{n.active?'Disable':'Activate'}</button></div></article>)}</div>{!ownFormNotices.length&&<EmptyState title="No public notices" text="Create notices from the Public Form tab."/>}</section>}
   {tab==='profile'&&<AgentProfile profile={profile} partner={partner} leads={leads} notes={profileNotes} events={events} onSaved={async()=>{await refreshProfile();load()}}/>}
  </main>
  {add&&<AgentLeadModal profile={profile} types={types} onClose={()=>setAdd(false)} onSaved={()=>{setAdd(false);load()}}/>}
  {leadEdit&&<LeadManageModal lead={leadEdit} profile={profile} onClose={()=>setLeadEdit(null)} onSaved={()=>{setLeadEdit(null);load()}}/>}
  {noticeEdit&&<AgentNoticeModal profile={profile} item={noticeEdit.id?noticeEdit:null} onClose={()=>setNoticeEdit(null)} onSaved={()=>{setNoticeEdit(null);load()}}/>}
 </div>
}

function AgentLeadTable({rows,onOpen}){return <div className="pro-table-panel-inner"><DataTable rows={rows} onRow={onOpen} columns={[{key:'sn',label:'SN',className:'pro-sn-col',align:'center',render:(_r,i)=><span className="pro-sn">{i+1}</span>},{key:'id',label:'Lead',render:r=><span className="pro-stack-cell"><b className="link">{r.id}</b><small>{r.source||'Agent Entry'}</small></span>},{key:'name',label:'Customer',render:r=><IdentityCell title={r.name} subtitle={r.phone}/>},{key:'route',label:'Route',render:r=><RouteCell from={r.pickup} to={r.drop} meta={r.goods||null}/>},{key:'vehicle_type',label:'Vehicle',render:r=><span className="pro-soft-chip">{r.vehicle_type||'TBD'}</span>},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>},{key:'created_at',label:'Created',render:r=><DateStack date={new Date(r.created_at).toLocaleDateString()} time={new Date(r.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}/>},{key:'action',label:'Action',className:'pro-action-col',align:'right',render:r=><RowActions onView={()=>onOpen(r)} viewLabel="Manage"/>}]}/></div>} 

function AgentLeadModal({profile,types,onClose,onSaved}){
 const [f,setF]=useState({name:'',phone:'',pickup:'',drop:'',goods:'',vehicle_type_id:'',vehicle_type:'',preferred_date:'',preferred_time:'',notes:''}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const save=async()=>{if(!f.name||!f.phone||!f.pickup||!f.drop)return setError('Name, phone, pickup and drop are required.');setBusy(true);setError('');try{const id=await nextId('lead');await insertRow('leads',{...f,id,status:'New Enquiry',source:'Agent Entry',referral_partner_id:profile.linked_entity_type==='referral_partner'?profile.linked_entity_id:null,referral_partner_name:profile.display_name,referral_code:profile.login_token,created_by_profile_id:profile.id,quote_history:[],followups:[],timeline:[]});await insertRow('lead_events',{lead_id:id,event_type:'Created',note:'Lead created from referral portal',actor_profile_id:profile.id});onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Modal open title="Add New Lead" subtitle="Capture the customer's route and requirement. This lead will automatically be attributed to your profile." onClose={onClose} size="lg" footer={<><button className="outline" onClick={onClose}>Cancel</button><button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save Lead'}</button></>}><div className="v25-form-stack"><FormSection title="Customer" description="Basic contact details"><div className="form-grid cols-2"><Field label="Full Name" required><input autoFocus value={f.name} onChange={e=>setF(x=>({...x,name:e.target.value}))}/></Field><Field label="Phone" required><input inputMode="tel" value={f.phone} onChange={e=>setF(x=>({...x,phone:e.target.value}))}/></Field></div></FormSection><FormSection title="Route & Requirement" description="Pickup, destination, goods and vehicle"><div className="form-grid cols-2"><Field label="Pickup" required><input value={f.pickup} onChange={e=>setF(x=>({...x,pickup:e.target.value}))}/></Field><Field label="Drop" required><input value={f.drop} onChange={e=>setF(x=>({...x,drop:e.target.value}))}/></Field><Field label="Goods / Load" full><input value={f.goods} onChange={e=>setF(x=>({...x,goods:e.target.value}))}/></Field><Field label="Vehicle"><select value={f.vehicle_type_id} onChange={e=>{const v=types.find(x=>x.id===e.target.value);setF(x=>({...x,vehicle_type_id:e.target.value,vehicle_type:v?.name||''}))}}><option value="">Not Decided</option>{types.map(v=><option key={v.id} value={v.id}>{v.icon||'🚚'} {v.name}</option>)}</select></Field><Field label="Preferred Date"><input type="date" value={f.preferred_date} onChange={e=>setF(x=>({...x,preferred_date:e.target.value}))}/></Field><Field label="Preferred Time"><input type="time" value={f.preferred_time} onChange={e=>setF(x=>({...x,preferred_time:e.target.value}))}/></Field><Field label="Notes" full><textarea rows="3" value={f.notes} onChange={e=>setF(x=>({...x,notes:e.target.value}))}/></Field></div></FormSection></div>{error&&<div className="form-error">{error}</div>}</Modal>
}

function LeadManageModal({lead,profile,onClose,onSaved}){
 const [status,setStatus]=useState(lead.status||'New Enquiry'),[note,setNote]=useState(''),[channel,setChannel]=useState('Call'),[nextDate,setNextDate]=useState(''),[nextTime,setNextTime]=useState(''),[followups,setFollowups]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{supabase.from('lead_followups').select('*').eq('lead_id',lead.id).order('created_at',{ascending:false}).limit(8).then(({data,error})=>{if(!error)setFollowups(data||[])})},[lead.id])
 const save=async()=>{setBusy(true);setError('');try{
   if(status!==lead.status)await updateRow('leads',lead.id,{status})
   if(note.trim()){
    const next=nextDate?new Date(`${nextDate}T${nextTime||'09:00'}:00+05:45`).toISOString():null
    await insertRow('lead_followups',{lead_id:lead.id,note:note.trim(),channel,next_followup_at:next,created_by:profile.id})
    await insertRow('lead_events',{lead_id:lead.id,event_type:'Follow-up',note:note.trim(),actor_profile_id:profile.id,metadata:{channel,next_followup_at:next,status}})
   }else if(status!==lead.status)await insertRow('lead_events',{lead_id:lead.id,event_type:'Status Update',note:`Status changed to ${status}`,actor_profile_id:profile.id,metadata:{from:lead.status,to:status}})
   onSaved()
  }catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Modal open title={`${lead.id} · ${lead.name}`} subtitle="Review this enquiry, update its status and schedule follow-up activity." onClose={onClose} size="xl" footer={<><button className="outline" onClick={onClose}>Close</button><button className="primary" onClick={save} disabled={busy}>{busy?'Saving…':'Save Update'}</button></>}>
  <div className="lead-manage-summary"><div><small>Phone</small><b>{lead.phone}</b></div><div><small>Route</small><b>{lead.pickup} → {lead.drop}</b></div><div><small>Vehicle</small><b>{lead.vehicle_type||'Not decided'}</b></div><div><small>Created</small><b>{formatDateTime(lead.created_at)}</b></div></div>
  <div className="v25-form-stack"><FormSection title="Lead status" description="Keep the current pipeline stage accurate."><div className="form-grid cols-2"><Field label="Status"><select value={status} disabled={lead.status==='Converted'} onChange={e=>setStatus(e.target.value)}>{['New Enquiry','Quoted','Confirmed','Converted','Lost','Cancelled'].map(x=><option key={x}>{x}</option>)}</select></Field></div></FormSection><FormSection title="Follow-up" description="Record the latest customer contact and optionally schedule the next follow-up."><div className="form-grid cols-2"><Field label="Channel"><select value={channel} onChange={e=>setChannel(e.target.value)}>{['Call','WhatsApp','SMS','Visit','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Next Follow-up Date"><input type="date" value={nextDate} onChange={e=>setNextDate(e.target.value)}/></Field><Field label="Next Follow-up Time"><input type="time" value={nextTime} onChange={e=>setNextTime(e.target.value)}/></Field><Field label="Follow-up Note" full><textarea rows="4" value={note} onChange={e=>setNote(e.target.value)} placeholder="Call result, customer response, next action…"/></Field></div></FormSection></div>
  {followups.length>0&&<section className="followup-history-mini"><div className="agent-section-head"><div><h3>Recent Follow-ups</h3><small>Latest activity on this lead</small></div><span className="chip">{followups.length}</span></div>{followups.map(f=><div className="followup-mini-row" key={f.id}><div><b>{f.channel||'Follow-up'}</b><span>{f.note}</span></div><div><small>{formatDateTime(f.created_at)}</small>{f.next_followup_at&&<em>Next: {formatDateTime(f.next_followup_at)}</em>}</div></div>)}</section>}
  {lead.notes&&<div className="muted-box mt"><b>Original Lead Notes</b><p>{lead.notes}</p></div>}{error&&<div className="form-error">{error}</div>}
 </Modal>
}

function AgentPublicForm({form,profile,qr,notices,onReload,onNewNotice,onEditNotice}){
 const [edit,setEdit]=useState(false)
 const create=async()=>{try{await insertRow('public_forms',{token:profile.login_token,owner_type:'Agent',owner_profile_id:profile.id,owner_display_name:profile.display_name,title:`Transport Enquiry · ${profile.display_name}`,subtitle:'Send your transport requirement directly.',intro_text:'Fill the form below and we will follow up with you.',submit_label:'Submit Enquiry',success_message:'Thank you. Your enquiry has been received.',settings:formDefaults,active:true,published_at:new Date().toISOString()});onReload()}catch(e){alert(e.message)}}
 if(!form)return <section className="agent-section public-form-empty"><div className="empty-feature-icon"><ExternalLink size={28}/></div><h2>Create your Public Lead Form</h2><p>Create a personal enquiry link and QR. Leads submitted from it are automatically attributed to your portal profile.</p><button className="primary" onClick={create}><Plus size={16}/> Create & Publish Form</button></section>
 const url=`${location.origin}/public/${form.token}`
 return <section className="agent-section"><div className="agent-section-head"><div><h3>Public Lead Form</h3><small>Your shareable enquiry page, QR and public notices.</small></div><div className="table-actions"><button className="outline" onClick={()=>setEdit(true)}><Settings2 size={16}/> Form Settings</button><button className={`switch-btn ${form.active?'on':'off'}`} onClick={async()=>{await updateRow('public_forms',form.id,{active:!form.active,published_at:!form.active?new Date().toISOString():form.published_at});onReload()}}>{form.active?'● Live':'○ Off'}</button></div></div><div className="public-form-card v25-public-form-card"><div><div className="public-share-card"><span className="qr-card-kicker public">PUBLIC LINK</span><h2>{form.title||'Transport Enquiry'}</h2><p>{form.subtitle||'Share this link with customers to collect transport enquiries.'}</p><code>{url}</code><div className="table-actions"><button className="primary small" onClick={()=>navigator.clipboard?.writeText(url)}>Copy Link</button><button className="outline small" onClick={()=>window.open(url,'_blank')}>Open Public Form</button>{qr&&<button className="outline small" onClick={()=>{const a=document.createElement('a');a.href=qr;a.download=`${form.token}-public-form-qr.png`;a.click()}}>Download QR</button>}</div></div><div className="agent-section-head mt"><div><h3>Public Notices</h3><small>Publish notices visible only on your form.</small></div><button className="outline small" onClick={onNewNotice}><Plus size={15}/> New Notice</button></div><div className="notice-library">{notices.map(n=><article key={n.id} className="notice-admin-card"><NoticeItem notice={n}/><div className="table-actions"><button className="outline small" onClick={()=>onEditNotice(n)}>Edit</button><button className="ghost small" onClick={async()=>{await updateRow('notices',n.id,{active:!n.active});onReload()}}>{n.active?'Disable':'Activate'}</button></div></article>)}</div>{!notices.length&&<EmptyState title="No public notice" text="Add an offer, service update or temporary notice."/>}</div><aside className="public-form-qr-panel">{qr&&<img src={qr}/>}<b>Scan to open form</b><small>{profile.display_name}</small><StatusBadge status={form.active?'Active':'Inactive'}/></aside></div>{edit&&<AgentFormSettingsModal form={form} onClose={()=>setEdit(false)} onSaved={()=>{setEdit(false);onReload()}}/>}</section>
}

function AgentFormSettingsModal({form,onClose,onSaved}){
 const [f,setF]=useState({...form,settings:{...formDefaults,...(form.settings||{})}}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const setSetting=(k,v)=>setF(x=>({...x,settings:{...x.settings,[k]:v}}))
 const save=async()=>{if(!f.title.trim())return setError('Form title is required.');setBusy(true);setError('');try{await updateRow('public_forms',form.id,{title:f.title,subtitle:f.subtitle||null,intro_text:f.intro_text||null,location_label:f.location_label||null,submit_label:f.submit_label||'Submit Enquiry',success_message:f.success_message||'Thank you. Your enquiry has been received.',settings:f.settings,active:f.active,published_at:f.active?(f.published_at||new Date().toISOString()):f.published_at});onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Modal open title="Public Form Settings" subtitle="Customize what customers see and which optional fields are shown." onClose={onClose} size="xl" footer={<><button className="outline" onClick={onClose}>Cancel</button><button className="primary" onClick={save} disabled={busy}>{busy?'Saving…':'Save Form Settings'}</button></>}><div className="v25-form-stack"><FormSection title="Public page content" description="Title, introduction and customer-facing messages"><div className="form-grid cols-2"><Field label="Form Title" required full><input value={f.title||''} onChange={e=>setF(x=>({...x,title:e.target.value}))}/></Field><Field label="Subtitle" full><input value={f.subtitle||''} onChange={e=>setF(x=>({...x,subtitle:e.target.value}))}/></Field><Field label="Intro Text" full><textarea rows="3" value={f.intro_text||''} onChange={e=>setF(x=>({...x,intro_text:e.target.value}))}/></Field><Field label="Location / Service Area"><input value={f.location_label||''} onChange={e=>setF(x=>({...x,location_label:e.target.value}))}/></Field><Field label="Submit Button"><input value={f.submit_label||''} onChange={e=>setF(x=>({...x,submit_label:e.target.value}))}/></Field><Field label="Success Message" full><textarea rows="2" value={f.success_message||''} onChange={e=>setF(x=>({...x,success_message:e.target.value}))}/></Field></div></FormSection><FormSection title="Field controls" description="Name, phone, pickup and drop remain required. Configure the optional fields below."><div className="switch-grid"><SwitchField label="Show Goods / Load" checked={!!f.settings.show_goods} onChange={v=>setSetting('show_goods',v)}/><SwitchField label="Require Goods / Load" checked={!!f.settings.require_goods} onChange={v=>setSetting('require_goods',v)}/><SwitchField label="Show Vehicle Type" checked={!!f.settings.show_vehicle} onChange={v=>setSetting('show_vehicle',v)}/><SwitchField label="Require Vehicle Type" checked={!!f.settings.require_vehicle} onChange={v=>setSetting('require_vehicle',v)}/><SwitchField label="Show Preferred Date / Time" checked={!!f.settings.show_schedule} onChange={v=>setSetting('show_schedule',v)}/><SwitchField label="Show Notes" checked={!!f.settings.show_notes} onChange={v=>setSetting('show_notes',v)}/></div></FormSection><FormSection title="Publishing" description="Turn your customer-facing page on or off."><SwitchField label="Public Form Live" description="When off, the public link shows Form unavailable." checked={f.active!==false} onChange={v=>setF(x=>({...x,active:v}))}/></FormSection></div>{error&&<div className="form-error">{error}</div>}</Modal>
}

function AgentNoticeModal({profile,item,onClose,onSaved}){
 const [f,setF]=useState({title:'',text:'',display_type:'Banner',semantic_type:'info',custom_color:'#1268f3',text_color:'#ffffff',icon:'🔔',priority:0,start_at:'',end_at:'',active:true,dismissible:true,cta_text:'',cta_action:'',marquee_speed:8,sort_order:0,...item}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const save=async()=>{if(!f.title||!f.text)return setError('Title and notice text are required.');setBusy(true);setError('');try{const row={...f,targets:['Agent Public Form'],audience:'Own Public Form',owner_type:'Agent',owner_profile_id:profile.id,created_by:profile.id,start_at:f.start_at?new Date(f.start_at).toISOString():null,end_at:f.end_at?new Date(f.end_at).toISOString():null,archived:false};item?.id?await updateRow('notices',item.id,row):await insertRow('notices',row);onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Modal open title={item?.id?'Edit Public Notice':'New Public Notice'} subtitle="Create a dynamic notice for customers opening your public form." onClose={onClose} size="lg" footer={<><button className="outline" onClick={onClose}>Cancel</button><button className="primary" onClick={save} disabled={busy}>{busy?'Saving…':'Save Notice'}</button></>}><div className="v25-form-stack"><FormSection title="Notice content" description="Message shown on your public enquiry page"><div className="form-grid cols-2"><Field label="Title" required full><input value={f.title} onChange={e=>setF(x=>({...x,title:e.target.value}))}/></Field><Field label="Notice Text" required full><textarea rows="3" value={f.text} onChange={e=>setF(x=>({...x,text:e.target.value}))}/></Field><Field label="Display Type"><select value={f.display_type} onChange={e=>setF(x=>({...x,display_type:e.target.value}))}>{['Banner','Marquee','Static','Highlight Card','Sticky Strip'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Semantic Type"><select value={f.semantic_type} onChange={e=>setF(x=>({...x,semantic_type:e.target.value}))}>{['info','success','warning','danger','custom'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Color"><input type="color" value={f.custom_color} onChange={e=>setF(x=>({...x,custom_color:e.target.value}))}/></Field><Field label="Icon"><input value={f.icon} onChange={e=>setF(x=>({...x,icon:e.target.value}))}/></Field></div></FormSection><FormSection title="Schedule & CTA" description="Optional time window and action button"><div className="form-grid cols-2"><Field label="Start"><input type="datetime-local" value={f.start_at||''} onChange={e=>setF(x=>({...x,start_at:e.target.value}))}/></Field><Field label="End"><input type="datetime-local" value={f.end_at||''} onChange={e=>setF(x=>({...x,end_at:e.target.value}))}/></Field><Field label="CTA Text"><input value={f.cta_text||''} onChange={e=>setF(x=>({...x,cta_text:e.target.value}))}/></Field><Field label="CTA Link"><input value={f.cta_action||''} onChange={e=>setF(x=>({...x,cta_action:e.target.value}))}/></Field></div><div className="notice-editor-preview mt"><NoticeItem notice={f}/></div></FormSection></div>{error&&<div className="form-error">{error}</div>}</Modal>
}

function AgentProfile({profile,partner,leads,notes=[],events=[],onSaved}){
 const [note,setNote]=useState(''),[category,setCategory]=useState('General'),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const add=async()=>{if(!note.trim())return;setBusy(true);setError('');try{await insertRow('profile_notes',{profile_type:'agent',record_id:profile.id,category,text:note.trim(),visibility:'Standard',author_profile_id:profile.id});setNote('');onSaved?.()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const converted=leads.filter(x=>x.status==='Converted').length
 return <div className="v25-profile-stack"><section className="agent-section"><div className="profile-hero compact"><div className="profile-avatar-lg">{initials(profile.display_name)}</div><div><small>{profile.profile_type||profile.role}</small><h2>{profile.display_name}</h2><p>{profile.mobile||'—'} · ID {profile.profile_id||'—'}</p></div></div><div className="agent-stats mt"><div><small>Total Leads</small><strong>{leads.length}</strong></div><div><small>Converted</small><strong>{converted}</strong></div><div><small>Conversion</small><strong>{leads.length?Math.round(converted/leads.length*100):0}%</strong></div><div><small>Status</small><strong>{profile.active?'Active':'Inactive'}</strong></div></div></section>{partner&&<section className="agent-section"><div className="agent-section-head"><div><h3>Referral Relationship</h3><small>Linked stakeholder and commission setup</small></div><StatusBadge status={partner.status||'Active'}/></div><div className="profile-info-grid"><div><small>Referral Partner ID</small><b>{partner.id}</b></div><div><small>Referral Code</small><b>{partner.referral_code||profile.login_token}</b></div><div><small>Commission</small><b>{partner.commission_type||'None'} {num(partner.commission_value)>0?partner.commission_value:''}</b></div><div><small>Earned / Paid</small><b>{money(partner.earned)} / {money(partner.paid)}</b></div></div></section>}<section className="agent-section"><div className="agent-section-head"><div><h3>Notes & Timeline</h3><small>Your own profile notes and recent lead activity.</small></div><span className="chip">{notes.length}</span></div><div className="note-compose"><select value={category} onChange={e=>setCategory(e.target.value)}>{['General','Performance','Payment','Job','Admin Note'].map(x=><option key={x}>{x}</option>)}</select><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Add profile note…"/><button className="primary" disabled={busy||!note.trim()} onClick={add}>{busy?'Saving…':'Add Note'}</button></div>{error&&<div className="form-error">{error}</div>}<div className="timeline-list mt">{notes.map(n=><div className="timeline-item" key={n.id}><span className="timeline-dot note"/><div className="timeline-card"><div className="timeline-meta"><span className="timeline-category">{n.category||'Note'}</span><span>{formatDateTime(n.created_at)}</span></div><p>{n.text}</p></div></div>)}{events.slice(0,10).map(e=><div className="timeline-item" key={e.id}><span className="timeline-dot"/><div className="timeline-card"><div className="timeline-meta"><span className="timeline-category">{e.event_type}</span><span>{formatDateTime(e.created_at)}</span></div><p>{e.note||'Lead activity'}</p></div></div>)}{!notes.length&&!events.length&&<div className="profile-empty">No activity yet.</div>}</div></section></div>
}
