import React,{useMemo,useState} from 'react'
import {useRealtimeTable} from '../hooks/useRealtimeTable'
import {insertRow,updateRow} from '../services/api'
import {useAuth} from '../contexts/AuthContext'
import {formatDateTime,money,num,todayKathmandu} from '../utils/format'
import PageTitle from '../components/PageTitle'
import DataTable from '../components/DataTable'
import Modal from '../components/Modal'

function dateOnly(v){return String(v||'').slice(0,10)}
export default function DayBook(){
 const {profile}=useAuth(),{rows:txns}=useRealtimeTable('transactions',{filters:[['archived','eq',false]]}),{rows:closings,reload}=useRealtimeTable('daybook_closings',{order:'date'})
 const [range,setRange]=useState('Daily'),[date,setDate]=useState(todayKathmandu()),[from,setFrom]=useState(todayKathmandu()),[to,setTo]=useState(todayKathmandu()),[search,setSearch]=useState(''),[type,setType]=useState('All'),[method,setMethod]=useState('All'),[sort,setSort]=useState('newest'),[view,setView]=useState('table'),[closeOpen,setCloseOpen]=useState(false)
 const filtered=useMemo(()=>{
  const q=search.toLowerCase(),d=new Date(`${date}T00:00:00`),start=new Date(d),end=new Date(d)
  if(range==='Weekly')start.setDate(d.getDate()-6)
  if(range==='Monthly')start.setDate(1)
  if(range==='All')start.setFullYear(2000)
  if(range==='Custom'){start.setTime(new Date(`${from}T00:00:00`).getTime());end.setTime(new Date(`${to}T23:59:59.999`).getTime())}else end.setHours(23,59,59,999)
  const a=txns.filter(t=>{const td=new Date(`${dateOnly(t.date||t.created_at)}T00:00:00`);return td>=start&&td<=end&&(type==='All'||t.direction===type)&&(method==='All'||t.method===method)&&(!q||[t.id,t.party_name,t.order_id,t.note,t.type].join(' ').toLowerCase().includes(q))})
  a.sort((a,b)=>sort==='oldest'?String(a.created_at||'').localeCompare(String(b.created_at||'')):sort==='amount-high'?num(b.amount)-num(a.amount):sort==='amount-low'?num(a.amount)-num(b.amount):String(b.created_at||'').localeCompare(String(a.created_at||'')))
  return a
 },[txns,range,date,from,to,search,type,method,sort])
 const active=filtered.filter(t=>t.status!=='Reversed'),receive=active.filter(t=>t.direction==='IN').reduce((s,t)=>s+num(t.amount),0),pay=active.filter(t=>t.direction==='OUT').reduce((s,t)=>s+num(t.amount),0),todayClose=closings.find(c=>c.date===date)
 return <>
  <PageTitle title="Day Book" subtitle="Daily, weekly, monthly and custom-range cash movement" actions={<button className="primary" onClick={()=>setCloseOpen(true)}>Close Day</button>}/>
  <div className="daybook-summary"><div><span>Opening</span><b>{money(0)}</b></div><div><span>Total Receive</span><b className="success-text">{money(receive)}</b></div><div><span>Total Pay</span><b className="danger-text">{money(pay)}</b></div><div><span>Net Movement</span><b>{money(receive-pay)}</b></div><div><span>Closing</span><b>{money(todayClose?.total??receive-pay)}</b></div><div><span>Verified</span><b>{todayClose?.verified_at?'Yes':'No'}</b></div></div>
  <div className="panel report-filter"><div className="filterbar daybook-toolbar"><select value={range} onChange={e=>setRange(e.target.value)}>{['Daily','Weekly','Monthly','Custom','All'].map(x=><option key={x}>{x}</option>)}</select>{range==='Custom'?<><input className="date-input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="date-input" type="date" value={to} onChange={e=>setTo(e.target.value)}/></>:<input className="date-input" type="date" value={date} onChange={e=>setDate(e.target.value)}/>}<label className="searchbox">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search transaction…"/></label><select value={type} onChange={e=>setType(e.target.value)}><option value="All">All Types</option><option value="IN">Receive</option><option value="OUT">Pay</option></select><select value={method} onChange={e=>setMethod(e.target.value)}>{['All','Cash','Bank','eSewa','Khalti','Credit','Other'].map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="amount-high">Amount High</option><option value="amount-low">Amount Low</option></select><div className="toggle-view"><button className={view==='table'?'active':''} onClick={()=>setView('table')}>▤</button><button className={view==='card'?'active':''} onClick={()=>setView('card')}>▦</button></div></div></div>
  {view==='table'?<section className="panel"><DataTable rows={filtered} columns={[{key:'sn',label:'SN',render:(_r,i)=>i+1},{key:'date',label:'Date'},{key:'id',label:'Transaction'},{key:'party_name',label:'Party'},{key:'type',label:'Type'},{key:'direction',label:'Flow',render:r=>r.direction==='IN'?'Receive':'Pay'},{key:'method',label:'Method'},{key:'amount',label:'Amount',render:r=><b className={r.direction==='IN'?'success-text':'danger-text'}>{money(r.amount)}</b>},{key:'status',label:'Status'},{key:'note',label:'Note'}]}/></section>:<div className="card-grid">{filtered.map(t=><article className="list-card" key={t.id}><div className="list-card-head"><b>{t.id}</b><span className={t.direction==='IN'?'success-text':'danger-text'}>{t.direction==='IN'?'Receive':'Pay'}</span></div><h3>{t.party_name||'General'}</h3><div className="card-line"><small>{t.method}</small><b>{money(t.amount)}</b></div><small>{formatDateTime(t.created_at)} · {t.status}</small></article>)}</div>}
  {closeOpen&&<CloseDay date={date} existing={todayClose} expected={receive-pay} profile={profile} onClose={()=>setCloseOpen(false)} onSaved={()=>{setCloseOpen(false);reload()}}/>}
 </>
}
function CloseDay({date,existing,expected,profile,onClose,onSaved}){const [f,setF]=useState({cash:existing?.cash||0,bank:existing?.bank||0,esewa:existing?.esewa||0,khalti:existing?.khalti||0,other:existing?.other||0,note:existing?.note||''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const total=['cash','bank','esewa','khalti','other'].reduce((s,k)=>s+num(f[k]),0),save=async()=>{setBusy(true);try{const row={date,...f,total,verified_by:profile?.id||null,verified_at:new Date().toISOString()};existing?.id?await updateRow('daybook_closings',existing.id,row):await insertRow('daybook_closings',row);onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}};return <Modal open title={`Close Day · ${date}`} onClose={onClose} footer={<><button className="outline" onClick={onClose}>Cancel</button><button className="primary" onClick={save} disabled={busy}>{busy?'Saving…':'Verify & Close'}</button></>}><div className="closing-preview"><span>Expected Closing</span><b>{money(expected)}</b><span>Actual Total</span><b>{money(total)}</b><span>Difference</span><b className={total-expected===0?'success-text':'danger-text'}>{money(total-expected)}</b></div><div className="form-grid cols-2">{['cash','bank','esewa','khalti','other'].map(k=><label className="field" key={k}><span>{k[0].toUpperCase()+k.slice(1)}</span><input type="number" value={f[k]} onChange={e=>setF(x=>({...x,[k]:e.target.value}))}/></label>)}<label className="field span-2"><span>Note</span><textarea value={f.note} onChange={e=>setF(x=>({...x,note:e.target.value}))}/></label></div>{error&&<div className="form-error">{error}</div>}</Modal>}