import React,{useMemo,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import {Play,CheckCircle2,Truck,ClipboardCheck} from 'lucide-react'
import {useRealtimeTable} from '../hooks/useRealtimeTable'
import {transitionOrder} from '../services/api'
import {formatDateTime,money} from '../utils/format'
import PageTitle from '../components/PageTitle'
import SearchFilterBar from '../components/SearchFilterBar'
import DataTable from '../components/DataTable'
import StatusBadge from '../components/StatusBadge'
import EmptyState from '../components/EmptyState'
import {DateStack,IdentityCell,MoneyCell,RouteCell,RowActions,SummaryCard,SummaryGrid} from '../components/TableKit'

const jobStages=['Assigned','Dispatched','In Transit','Delivered','Completed']
export default function Jobs(){
 const nav=useNavigate(),{rows,reload}=useRealtimeTable('orders',{filters:[['archived','eq',false],['status','in',jobStages]],order:'updated_at'})
 const [search,setSearch]=useState(''),[status,setStatus]=useState('All'),[sort,setSort]=useState('newest'),[view,setView]=useState('table'),[busy,setBusy]=useState(''),[error,setError]=useState('')
 const filtered=useMemo(()=>{const q=search.toLowerCase();const list=rows.filter(o=>(status==='All'||o.status===status)&&(!q||[o.id,o.customer,o.phone,o.pickup,o.drop,o.vehicle_type,o.driver_name].join(' ').toLowerCase().includes(q)));return [...list].sort((a,b)=>sort==='oldest'?String(a.updated_at||a.created_at||'').localeCompare(String(b.updated_at||b.created_at||'')):sort==='customer'?String(a.customer||'').localeCompare(String(b.customer||'')):String(b.updated_at||b.created_at||'').localeCompare(String(a.updated_at||a.created_at||'')))},[rows,search,status,sort])
 const act=async(o,target)=>{if(busy)return;setBusy(o.id);setError('');try{await transitionOrder(o.id,target,target==='In Transit'?'Trip started':target==='Delivered'?'Delivery marked':'Operational job completed');await reload({silent:true})}catch(e){setError(e.message||'Unable to update job stage.')}finally{setBusy('')}}
 const action=o=>o.status==='Assigned'?<button className="outline small" onClick={()=>nav(`/dispatch?order=${o.id}`)}>Open Dispatch</button>:o.status==='Dispatched'?<button className="primary small" disabled={busy===o.id} onClick={()=>act(o,'In Transit')}><Play size={14}/> Start Trip</button>:o.status==='In Transit'?<button className="primary small" disabled={busy===o.id} onClick={()=>act(o,'Delivered')}><Truck size={14}/> Delivered</button>:o.status==='Delivered'?<button className="primary small" disabled={busy===o.id} onClick={()=>act(o,'Completed')}><CheckCircle2 size={14}/> Complete</button>:<button className="outline small" onClick={()=>nav(`/orders/${o.id}`)}>View</button>
 const columns=[{key:'sn',label:'SN',className:'pro-sn-col',align:'center',render:(_r,i)=><span className="pro-sn">{i+1}</span>},{key:'id',label:'Job / Order',render:o=><span className="pro-stack-cell"><b className="link">{o.id}</b><small>{formatDateTime(o.assigned_at||o.created_at)}</small></span>},{key:'customer',label:'Customer',render:o=><IdentityCell title={o.customer} subtitle={o.phone||'—'}/>},{key:'route',label:'Route',render:o=><RouteCell from={o.pickup} to={o.drop} meta={o.goods||null}/>},{key:'vehicle_type',label:'Vehicle / Driver',render:o=><span className="pro-stack-cell"><b>{o.vehicle_type||'—'}</b><small>{o.driver_name||'Driver not assigned'}</small></span>},{key:'customer_rate',label:'Rate',align:'right',render:o=><MoneyCell value={o.customer_rate}/>},{key:'status',label:'Stage',render:o=><StatusBadge status={o.status}/>},{key:'action',label:'Next Action',className:'pro-action-col',align:'right',render:o=><div className="pro-action-combo">{action(o)}<RowActions onView={()=>nav(`/orders/${o.id}`)} viewLabel="Details"/></div>}]
 const assigned=rows.filter(x=>x.status==='Assigned').length,active=rows.filter(x=>['Dispatched','In Transit'].includes(x.status)).length,delivered=rows.filter(x=>x.status==='Delivered').length,completed=rows.filter(x=>x.status==='Completed').length
 return <>
  <PageTitle title="Jobs" subtitle="Operational work after assignment — assignment is not the same as work started" actions={<button className="outline" onClick={()=>nav('/dispatch')}>Open Dispatch</button>}/>
  <SummaryGrid className="compact"><SummaryCard icon={<ClipboardCheck size={17}/>} label="Assigned" value={assigned} note="Ready for dispatch"/><SummaryCard icon={<Play size={17}/>} label="Active Trips" value={active} note="Dispatched / In Transit" tone={active?'success':''}/><SummaryCard icon={<Truck size={17}/>} label="Delivered" value={delivered} note="Operationally finished"/><SummaryCard icon={<CheckCircle2 size={17}/>} label="Completed" value={completed} note={`${rows.length} jobs in view`} tone="success"/></SummaryGrid>
  {error&&<div className="form-error">{error}</div>}
  <SearchFilterBar search={search} onSearch={setSearch} view={view} onView={setView} placeholder="Search job, order, customer, route, vehicle…" className="pro-module-toolbar" onReset={()=>{setSearch('');setStatus('All');setSort('newest')}}><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{jobStages.map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="customer">Customer A–Z</option></select></SearchFilterBar>
  {!filtered.length?<EmptyState title="No jobs in this view" text="Assigned and active operational orders appear here."/>:view==='table'?<section className="panel pro-table-panel"><DataTable rows={filtered} columns={columns} onRow={o=>nav(`/orders/${o.id}`)}/></section>:<div className="pro-card-grid">{filtered.map(o=><article className="pro-record-card job-card" key={o.id} onClick={()=>nav(`/orders/${o.id}`)}><header><IdentityCell title={o.customer} subtitle={o.phone||'—'} meta={o.id}/><StatusBadge status={o.status}/></header><div className="pro-route-box">{o.pickup} <span>→</span> {o.drop}</div><div className="pro-record-kvs"><div><small>Vehicle</small><b>{o.vehicle_type||'—'}</b></div><div><small>Driver</small><b>{o.driver_name||'—'}</b></div><div><small>Rate</small><b>{money(o.customer_rate)}</b></div></div><footer onClick={e=>e.stopPropagation()}>{action(o)}<RowActions onView={()=>nav(`/orders/${o.id}`)} viewLabel="Details"/></footer></article>)}</div>}
 </>
}
