import React,{useEffect,useState} from 'react'
import QRCode from 'qrcode'
import {ExternalLink,Plus,Settings2} from 'lucide-react'
import {useRealtimeTable} from '../hooks/useRealtimeTable'
import {insertRow,updateRow} from '../services/api'
import {useAuth} from '../contexts/AuthContext'
import PageTitle from '../components/PageTitle'
import NoticeRenderer from '../components/NoticeRenderer'
import StatusBadge from '../components/StatusBadge'
import Modal from '../components/Modal'
import {Field,FormSection,SwitchField} from '../components/FormKit'

const defaults={show_goods:true,show_vehicle:true,show_schedule:true,show_notes:false,require_goods:false,require_vehicle:false}
export default function PublicFormSettings(){
 const {profile}=useAuth(),{rows,reload}=useRealtimeTable('public_forms',{filters:[['owner_type','eq','Admin']]}),{rows:notices}=useRealtimeTable('notices',{filters:[['archived','eq',false]]})
 const form=rows[0],[edit,setEdit]=useState(false),[qr,setQr]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(form){const url=`${location.origin}/public/${form.token}`;QRCode.toDataURL(url,{width:280,margin:1}).then(setQr)}},[form?.id,form?.updated_at])
 const create=async()=>{setBusy(true);setError('');try{const token=`DIRECT-${crypto.randomUUID().replace(/-/g,'').slice(0,8).toUpperCase()}`;await insertRow('public_forms',{token,owner_type:'Admin',owner_profile_id:profile?.id||null,owner_display_name:'RikshaMS',title:'Transport Enquiry',subtitle:'Send your transport requirement directly.',intro_text:'Fill the form below and our team will contact you.',submit_label:'Submit Enquiry',success_message:'Thank you. Your enquiry has been received.',settings:defaults,active:true,published_at:new Date().toISOString()});reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(!form)return <><PageTitle title="Direct Public Form" subtitle="Admin-owned public lead form"/><section className="panel public-form-empty"><div className="empty-feature-icon"><ExternalLink size={28}/></div><h2>Create Direct Public Form</h2><p>Create the main public enquiry link and QR for customers who are not coming through a referral agent.</p><button className="primary" disabled={busy} onClick={create}><Plus size={16}/> {busy?'Creating…':'Create & Publish Form'}</button>{error&&<div className="form-error mt">{error}</div>}</section></>
 const url=`${location.origin}/public/${form.token}`,activeNotices=notices.filter(n=>n.active&&Array.isArray(n.targets)&&n.targets.includes('Direct Public Form'))
 return <><PageTitle title="Direct Public Form" subtitle="Public enquiry form, field controls, share link and QR" actions={<button className="primary" onClick={()=>setEdit(true)}><Settings2 size={16}/> Form Settings</button>}/><div className="public-settings-grid"><section className="panel"><div className="panel-head"><div><h3>{form.title}</h3><small>{form.subtitle||'Direct enquiry form'}</small></div><button className={`switch-btn ${form.active?'on':'off'}`} onClick={async()=>{await updateRow('public_forms',form.id,{active:!form.active,published_at:!form.active?new Date().toISOString():form.published_at});reload()}}>{form.active?'● Enabled':'○ Disabled'}</button></div><div className="public-url-box mt"><small>{url}</small><button className="outline small" onClick={()=>navigator.clipboard?.writeText(url)}>Copy</button><button className="outline small" onClick={()=>window.open(url,'_blank')}>Open</button>{qr&&<button className="outline small" onClick={()=>{const a=document.createElement('a');a.href=qr;a.download='rikshams-direct-public-form-qr.png';a.click()}}>Download QR</button>}</div>{qr&&<img className="public-qr" src={qr}/>}<div className="muted-box mt"><b>How it works</b><p>Share this link or QR. New submissions enter Leads & Enquiries with source “Direct Public Form”.</p></div></section><aside className="public-form-preview panel"><div className="public-form-status"><div><b>{form.title}</b><small>{form.subtitle||''}</small></div><StatusBadge status={form.active?'Active':'Inactive'}/></div><NoticeRenderer notices={activeNotices}/><div className="public-preview-fields"><span>Full Name *</span><span>Phone *</span><span>Pickup *</span><span>Drop *</span>{(form.settings?.show_goods??true)&&<span>Goods / Load</span>}{(form.settings?.show_vehicle??true)&&<span>Vehicle Type</span>}{(form.settings?.show_schedule??true)&&<><span>Preferred Date</span><span>Preferred Time</span></>}</div></aside></div>{edit&&<DirectFormModal form={form} onClose={()=>setEdit(false)} onSaved={()=>{setEdit(false);reload()}}/>}</>
}

function DirectFormModal({form,onClose,onSaved}){
 const [f,setF]=useState({...form,settings:{...defaults,...(form.settings||{})}}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const setSetting=(k,v)=>setF(x=>({...x,settings:{...x.settings,[k]:v}}))
 const save=async()=>{if(!f.title.trim())return setError('Form title is required.');setBusy(true);setError('');try{await updateRow('public_forms',form.id,{title:f.title,subtitle:f.subtitle||null,intro_text:f.intro_text||null,location_label:f.location_label||null,submit_label:f.submit_label||'Submit Enquiry',success_message:f.success_message||'Thank you. Your enquiry has been received.',settings:f.settings,active:f.active});onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Modal open title="Direct Public Form Settings" subtitle="Customize public copy, optional fields and publishing state." onClose={onClose} size="xl" footer={<><button className="outline" onClick={onClose}>Cancel</button><button className="primary" onClick={save} disabled={busy}>{busy?'Saving…':'Save Form Settings'}</button></>}><div className="v25-form-stack"><FormSection title="Public page content" description="Customer-facing copy"><div className="form-grid cols-2"><Field label="Form Title" required full><input value={f.title||''} onChange={e=>setF(x=>({...x,title:e.target.value}))}/></Field><Field label="Subtitle" full><input value={f.subtitle||''} onChange={e=>setF(x=>({...x,subtitle:e.target.value}))}/></Field><Field label="Intro Text" full><textarea rows="3" value={f.intro_text||''} onChange={e=>setF(x=>({...x,intro_text:e.target.value}))}/></Field><Field label="Location / Service Area"><input value={f.location_label||''} onChange={e=>setF(x=>({...x,location_label:e.target.value}))}/></Field><Field label="Submit Button"><input value={f.submit_label||''} onChange={e=>setF(x=>({...x,submit_label:e.target.value}))}/></Field><Field label="Success Message" full><textarea rows="2" value={f.success_message||''} onChange={e=>setF(x=>({...x,success_message:e.target.value}))}/></Field></div></FormSection><FormSection title="Field controls" description="Name, phone, pickup and drop are always required."><div className="switch-grid"><SwitchField label="Show Goods / Load" checked={!!f.settings.show_goods} onChange={v=>setSetting('show_goods',v)}/><SwitchField label="Require Goods / Load" checked={!!f.settings.require_goods} onChange={v=>setSetting('require_goods',v)}/><SwitchField label="Show Vehicle Type" checked={!!f.settings.show_vehicle} onChange={v=>setSetting('show_vehicle',v)}/><SwitchField label="Require Vehicle Type" checked={!!f.settings.require_vehicle} onChange={v=>setSetting('require_vehicle',v)}/><SwitchField label="Show Preferred Date / Time" checked={!!f.settings.show_schedule} onChange={v=>setSetting('show_schedule',v)}/><SwitchField label="Show Notes" checked={!!f.settings.show_notes} onChange={v=>setSetting('show_notes',v)}/></div></FormSection><FormSection title="Publishing" description="Control whether the link is accepting enquiries."><SwitchField label="Public Form Live" checked={f.active!==false} onChange={v=>setF(x=>({...x,active:v}))}/></FormSection></div>{error&&<div className="form-error">{error}</div>}</Modal>
}
