import React,{useMemo,useState} from 'react'
import {ArrowDownToLine,ArrowUpFromLine,Banknote,ChartNoAxesCombined,CircleDollarSign,Scale} from 'lucide-react'
import {useRealtimeTable} from '../hooks/useRealtimeTable'
import {formatDateTime,money,num,todayKathmandu} from '../utils/format'
import {activeTransactions,orderFinancial,orderBill,orderCost,portfolioFinancial,txnDate} from '../utils/accounting'
import PageTitle from '../components/PageTitle'
import SearchFilterBar from '../components/SearchFilterBar'
import DataTable from '../components/DataTable'
import StatusBadge from '../components/StatusBadge'
import {IdentityCell,MoneyCell,RouteCell,DateStack} from '../components/TableKit'

function inRange(row,range,from,to){if(range==='All')return true;const raw=row.date||row.created_at||row.updated_at;if(!raw)return false;const d=new Date(String(raw).length===10?`${raw}T00:00:00`:raw),now=new Date();if(range==='Today')return d.toDateString()===now.toDateString();if(range==='This Week'){const s=new Date(now);s.setHours(0,0,0,0);s.setDate(now.getDate()-6);return d>=s&&d<=now}if(range==='This Month')return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth();if(range==='Custom'){const a=new Date(`${from}T00:00:00`),b=new Date(`${to}T23:59:59.999`);return d>=a&&d<=b}return true}
const tabs=[['overview','Overview'],['customer','Customer Due'],['payable','Resource Payable'],['transactions','Transactions'],['profit','Order Profit']]

export default function Reports(){
 const {rows:orders}=useRealtimeTable('orders',{filters:[['archived','eq',false]]})
 const {rows:txns}=useRealtimeTable('transactions',{filters:[['archived','eq',false]]})
 const {rows:leads}=useRealtimeTable('leads',{filters:[['archived','eq',false]]})
 const [tab,setTab]=useState('overview'),[range,setRange]=useState('All'),[from,setFrom]=useState(todayKathmandu()),[to,setTo]=useState(todayKathmandu()),[search,setSearch]=useState(''),[sort,setSort]=useState('newest'),[view,setView]=useState('table')
 const ro=useMemo(()=>orders.filter(x=>inRange(x,range,from,to)&&x.status!=='Cancelled'),[orders,range,from,to]),rt=useMemo(()=>txns.filter(x=>inRange(x,range,from,to)),[txns,range,from,to]),rl=useMemo(()=>leads.filter(x=>inRange(x,range,from,to)),[leads,range,from,to])
 const orderIds=new Set(ro.map(x=>x.id)),relatedTx=txns.filter(t=>t.order_id&&orderIds.has(t.order_id)),finance=portfolioFinancial(ro,relatedTx),cashTx=activeTransactions(rt),cashReceive=cashTx.filter(t=>t.direction==='IN').reduce((s,t)=>s+num(t.amount),0),cashPay=cashTx.filter(t=>t.direction==='OUT').reduce((s,t)=>s+num(t.amount),0),completed=ro.filter(o=>o.status==='Completed').length,converted=rl.filter(l=>l.status==='Converted').length
 const orderRows=useMemo(()=>ro.map(o=>({...o,_fin:orderFinancial(o,txns)})),[ro,txns])
 const q=search.toLowerCase()
 const sortRows=list=>[...list].sort((a,b)=>sort==='oldest'?String(a.created_at||a.date||'').localeCompare(String(b.created_at||b.date||'')):sort==='amount-high'?num(b._amount??b.amount)-num(a._amount??a.amount):sort==='amount-low'?num(a._amount??a.amount)-num(b._amount??b.amount):String(b.created_at||b.date||'').localeCompare(String(a.created_at||a.date||'')))
 const dueRows=sortRows(orderRows.filter(o=>o._fin.receivable>0.004&&(!q||[o.id,o.customer,o.phone,o.pickup,o.drop].join(' ').toLowerCase().includes(q))).map(o=>({...o,_amount:o._fin.receivable})))
 const payableRows=sortRows(orderRows.filter(o=>o._fin.payable>0.004&&(!q||[o.id,o.customer,o.vehicle_type,o.driver_name].join(' ').toLowerCase().includes(q))).map(o=>({...o,_amount:o._fin.payable})))
 const profitRows=sortRows(orderRows.filter(o=>!q||[o.id,o.customer,o.pickup,o.drop,o.vehicle_type].join(' ').toLowerCase().includes(q)).map(o=>({...o,_amount:o._fin.accruedMargin})))
 const txRows=sortRows(rt.filter(t=>!q||[t.id,t.order_id,t.party_name,t.party_type,t.type,t.method,t.note].join(' ').toLowerCase().includes(q)).map(t=>({...t,_amount:num(t.amount)})))
 const byStatus=['New','Assigned','Dispatched','In Transit','Delivered','Completed'].map(s=>({status:s,count:ro.filter(o=>o.status===s).length,value:ro.filter(o=>o.status===s).reduce((a,o)=>a+orderBill(o),0)}))
 const renderCards=(rows,kind)=> <div className="card-grid">{rows.map(r=><article className="list-card" key={r.id}><div className="list-card-head"><b>{r.id}</b>{r.status&&<StatusBadge status={r.status}/>}</div><h3>{r.customer||r.party_name||'General'}</h3>{r.order_id&&<p className="muted">Order {r.order_id}</p>}{kind!=='transactions'&&<div className="route-card">{r.pickup||'—'} → {r.drop||'—'}</div>}<div className="card-line"><small>{kind==='customer'?'Customer Due':kind==='payable'?'Resource Payable':kind==='profit'?'Accrued Margin':r.direction==='IN'?'Receive':'Pay'}</small><b className={kind==='transactions'?(r.direction==='IN'?'success-text':'danger-text'):''}>{money(kind==='customer'?r._fin.receivable:kind==='payable'?r._fin.payable:kind==='profit'?r._fin.accruedMargin:r.amount)}</b></div><small>{formatDateTime(r.created_at)}</small></article>)}</div>
 return <>
  <PageTitle title="Accounts & Reports" subtitle="Receivables, payables, cash flow, margins and operational performance" actions={<button className="outline" onClick={()=>window.print()}>Print Report</button>}/>
  <div className="master-tabs report-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div>
  <div className="accounting-kpi-grid"><div><span><CircleDollarSign size={16}/> Booked Revenue</span><b>{money(finance.bookedRevenue)}</b><small>Selected non-cancelled orders</small></div><div><span><ArrowDownToLine size={16}/> Received</span><b>{money(finance.received)}</b><small>Effective receipts linked to orders</small></div><div><span><Banknote size={16}/> Customer Due</span><b>{money(finance.receivable)}</b><small>Outstanding receivable</small></div><div><span><ArrowUpFromLine size={16}/> Committed Cost</span><b>{money(finance.committedCost)}</b><small>Vehicle + labour + operating cost</small></div><div><span><Scale size={16}/> Resource Payable</span><b>{money(finance.payable)}</b><small>Outstanding resource cost</small></div><div><span><ChartNoAxesCombined size={16}/> Accrued Margin</span><b>{money(finance.accruedMargin)}</b><small>Booked revenue less committed cost</small></div></div>
  <SearchFilterBar search={search} onSearch={setSearch} view={tab==='overview'?null:view} onView={tab==='overview'?null:setView} placeholder="Search order, customer, party or transaction…" className="pro-module-toolbar" onReset={()=>{setSearch('');setSort('newest');setRange('All')}}><select value={range} onChange={e=>setRange(e.target.value)}>{['All','Today','This Week','This Month','Custom'].map(x=><option key={x}>{x}</option>)}</select>{range==='Custom'&&<><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></>}<select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="amount-high">Amount High</option><option value="amount-low">Amount Low</option></select></SearchFilterBar>
  {tab==='overview'&&<div className="grid-2"><section className="panel"><div className="panel-head"><div><h3>Cash Flow in Selected Period</h3><small>Actual effective transaction movement</small></div></div><div className="money-stack"><div><span>Total Receive</span><b className="success-text">{money(cashReceive)}</b></div><div><span>Total Pay</span><b className="danger-text">{money(cashPay)}</b></div><div className="total"><span>Net Cash Movement</span><b>{money(cashReceive-cashPay)}</b></div><div><span>Completed Orders</span><b>{completed}/{ro.length}</b></div><div><span>Lead Conversion</span><b>{rl.length?Math.round(converted/rl.length*100):0}%</b></div></div></section><section className="panel pro-table-panel"><div className="panel-head"><div><h3>Order Stage Portfolio</h3><small>Value and count by current stage</small></div></div><DataTable className="compact-pro-table" rows={byStatus} columns={[{key:'sn',label:'SN',className:'pro-sn-col',align:'center',render:(_r,i)=><span className="pro-sn">{i+1}</span>},{key:'status',label:'Stage',render:r=><StatusBadge status={r.status}/>},{key:'count',label:'Orders',align:'center',render:r=><span className="pro-count-badge">{r.count}</span>},{key:'value',label:'Booked Value',align:'right',render:r=><MoneyCell value={r.value}/>} ]}/></section></div>}
  {tab==='customer'&&(view==='table'?<section className="panel pro-table-panel"><DataTable rows={dueRows} columns={[{key:'sn',label:'SN',className:'pro-sn-col',align:'center',render:(_r,i)=><span className="pro-sn">{i+1}</span>},{key:'id',label:'Order',render:r=><b className="link">{r.id}</b>},{key:'customer',label:'Customer',render:r=><IdentityCell title={r.customer} subtitle={r.phone||'—'}/>},{key:'route',label:'Route',render:r=><RouteCell from={r.pickup} to={r.drop}/>},{key:'bill',label:'Bill',align:'right',render:r=><MoneyCell value={r._fin.bill}/>},{key:'received',label:'Received',align:'right',render:r=><MoneyCell value={r._fin.received} tone="success"/>},{key:'due',label:'Due',align:'right',render:r=><MoneyCell value={r._fin.receivable} tone="danger" label="Due"/>},{key:'status',label:'Order Status',render:r=><StatusBadge status={r.status}/>} ]}/></section>:renderCards(dueRows,'customer'))}
  {tab==='payable'&&(view==='table'?<section className="panel pro-table-panel"><DataTable rows={payableRows} columns={[{key:'sn',label:'SN',className:'pro-sn-col',align:'center',render:(_r,i)=><span className="pro-sn">{i+1}</span>},{key:'id',label:'Order',render:r=><b className="link">{r.id}</b>},{key:'customer',label:'Customer',render:r=><IdentityCell title={r.customer} subtitle={r.driver_name||'No driver'}/>},{key:'vehicle_type',label:'Vehicle',render:r=><span className="pro-soft-chip">{r.vehicle_type||'—'}</span>},{key:'cost',label:'Committed Cost',align:'right',render:r=><MoneyCell value={r._fin.cost}/>},{key:'paid',label:'Paid',align:'right',render:r=><MoneyCell value={r._fin.paid} tone="success"/>},{key:'payable',label:'Payable',align:'right',render:r=><MoneyCell value={r._fin.payable} tone="danger" label="Payable"/>},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>} ]}/></section>:renderCards(payableRows,'payable'))}
  {tab==='transactions'&&(view==='table'?<section className="panel pro-table-panel"><DataTable rows={txRows} columns={[{key:'sn',label:'SN',className:'pro-sn-col',align:'center',render:(_r,i)=><span className="pro-sn">{i+1}</span>},{key:'id',label:'Transaction',render:r=><span className="pro-stack-cell"><b className="link">{r.id}</b><small>{r.order_id||'General'}</small></span>},{key:'date',label:'Date',render:r=><DateStack date={txnDate(r)}/>},{key:'party_name',label:'Party',render:r=><IdentityCell title={r.party_name||'—'} subtitle={r.party_type||'—'}/>},{key:'direction',label:'Flow',render:r=><span className={`flow-pill ${r.direction==='IN'?'receive':'pay'}`}>{r.direction==='IN'?'Receive':'Pay'}</span>},{key:'method',label:'Method'},{key:'amount',label:'Amount',align:'right',render:r=><MoneyCell value={r.amount} tone={r.direction==='IN'?'success':'danger'}/>},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>} ]}/></section>:renderCards(txRows,'transactions'))}
  {tab==='profit'&&(view==='table'?<section className="panel pro-table-panel"><DataTable rows={profitRows} columns={[{key:'sn',label:'SN',className:'pro-sn-col',align:'center',render:(_r,i)=><span className="pro-sn">{i+1}</span>},{key:'id',label:'Order',render:r=><b className="link">{r.id}</b>},{key:'customer',label:'Customer',render:r=><IdentityCell title={r.customer} subtitle={r.vehicle_type||'—'}/>},{key:'bill',label:'Revenue',align:'right',render:r=><MoneyCell value={orderBill(r)}/>},{key:'cost',label:'Cost',align:'right',render:r=><MoneyCell value={orderCost(r)} tone="danger"/>},{key:'margin',label:'Margin',align:'right',render:r=><MoneyCell value={r._fin.accruedMargin} tone={r._fin.accruedMargin>=0?'success':'danger'}/>},{key:'cashMargin',label:'Cash Margin',align:'right',render:r=><MoneyCell value={r._fin.cashMargin}/>},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>} ]}/></section>:renderCards(profitRows,'profit'))}
 </>
}
