import React,{useMemo,useState} from 'react'
import {useRealtimeTable} from '../hooks/useRealtimeTable'
import {formatDateTime,money} from '../utils/format'
import {supabase} from '../lib/supabase'
import PageTitle from '../components/PageTitle'
import SearchFilterBar from '../components/SearchFilterBar'
import DataTable from '../components/DataTable'
import Modal from '../components/Modal'
import StatusBadge from '../components/StatusBadge'
export default function Slips(){const {rows}=useRealtimeTable('slips',{filters:[['archived','eq',false]]}),[search,setSearch]=useState(''),[type,setType]=useState('All'),[view,setView]=useState('table'),[selected,setSelected]=useState(null);const filtered=useMemo(()=>{const q=search.toLowerCase();return rows.filter(s=>(type==='All'||s.type===type)&&(!q||[s.slip_no,s.order_id,s.customer_name,s.customer_phone].join(' ').toLowerCase().includes(q)))},[rows,search,type]);return <><PageTitle title="Slips" subtitle="Order Slip, Dispatch Slip and Receipt records"/><SearchFilterBar search={search} onSearch={setSearch} view={view} onView={setView} placeholder="Search slip, order, customer…"><select value={type} onChange={e=>setType(e.target.value)}>{['All','ORDER','DISPATCH','RECEIPT'].map(x=><option key={x}>{x}</option>)}</select></SearchFilterBar>{view==='table'?<section className="panel"><DataTable rows={filtered} columns={[{key:'sn',label:'SN',render:(_r,i)=>i+1},{key:'slip_no',label:'Slip',render:r=><b>{r.slip_no}</b>},{key:'type',label:'Type'},{key:'order_id',label:'Order'},{key:'customer_name',label:'Customer',render:r=><><b>{r.customer_name}</b><small>{r.customer_phone}</small></>},{key:'amount',label:'Amount',render:r=>r.amount?money(r.amount):'—'},{key:'status',label:'Status',render:r=><StatusBadge status={r.status}/>},{key:'created_at',label:'Created',render:r=>formatDateTime(r.created_at)},{key:'action',label:'Action',render:r=><button className="outline small" onClick={()=>setSelected(r)}>View</button>}]}/></section>:<div className="card-grid">{filtered.map(s=><article className="list-card" key={s.id}><div className="list-card-head"><b>{s.slip_no}</b><StatusBadge status={s.status}/></div><h3>{s.type}</h3><span>{s.customer_name}</span><div className="card-line"><small>Order</small><b>{s.order_id}</b></div><button className="outline small" onClick={()=>setSelected(s)}>View</button></article>)}</div>}{selected&&<SlipModal slip={selected} onClose={()=>setSelected(null)}/>}</>}
function SlipModal({slip,onClose}){const s=slip.snapshot||{},print=async()=>{try{await supabase.from('slips').update({print_count:Number(slip.print_count||0)+1,last_printed_at:new Date().toISOString()}).eq('id',slip.id)}catch(e){}const w=window.open('','_blank','width=900,height=900');w.document.write(`<html><head><title>${slip.slip_no}</title><style>body{font-family:Arial;padding:24px;color:#101828}.paper{max-width:760px;margin:auto;border:1px solid #dfe5ed;padding:28px}.head{display:flex;justify-content:space-between;border-bottom:3px solid #1268f3;padding-bottom:14px}.brand h1{margin:0;color:#0b1f38}.title{text-align:right}table{width:100%;border-collapse:collapse;margin-top:18px}td{padding:9px;border-bottom:1px solid #eee}.route{font-size:18px;font-weight:700;padding:18px;background:#f5f8fc;margin:16px 0}.foot{margin-top:35px;display:flex;justify-content:space-between}</style></head><body><div class="paper"><div class="head"><div class="brand"><h1>RikshaMS</h1><span>Transport Management</span></div><div class="title"><b>${slip.type} SLIP</b><div>${slip.slip_no}</div></div></div><div class="route">${s.pickup||'—'} → ${s.drop||'—'}</div><table>${Object.entries(s).filter(([k,v])=>typeof v!=='object').map(([k,v])=>`<tr><td>${k}</td><td><b>${v??'—'}</b></td></tr>`).join('')}</table><div class="foot"><span>Customer Signature</span><span>Authorized Signature</span></div></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()};return <Modal open title={`${slip.type} · ${slip.slip_no}`} onClose={onClose} size="lg" footer={<><button className="outline" onClick={onClose}>Close</button><button className="primary" onClick={print}>Print</button></>}><div className="slip-preview"><div className="slip-brand"><div><h2>RikshaMS</h2><small>Transport Management</small></div><b>{slip.type} SLIP</b></div><div className="route-card big">{s.pickup||'—'} → {s.drop||'—'}</div><div className="profile-info-grid">{Object.entries(s).filter(([k,v])=>typeof v!=='object').map(([k,v])=><div key={k}><small>{k.replaceAll(/([A-Z])/g,' $1')}</small><b>{String(v??'—')}</b></div>)}</div></div></Modal>}