import React from 'react'
import {BrowserRouter,Navigate,Route,Routes,useLocation} from 'react-router-dom'
import {AuthProvider,useAuth} from './contexts/AuthContext'
import AppShell from './layouts/AppShell'
import Login from './pages/Login'
import Dashboard from './pages/Dashboard'
import Leads from './pages/Leads'
import NewOrder from './pages/NewOrder'
import Orders from './pages/Orders'
import Dispatch from './pages/Dispatch'
import Fleet from './pages/Fleet'
import Customers from './pages/Customers'
import ReceivePay from './pages/ReceivePay'
import DayBook from './pages/DayBook'
import Slips from './pages/Slips'
import Reports from './pages/Reports'
import Access from './pages/Access'
import NoticeCenter from './pages/NoticeCenter'
import Settings from './pages/Settings'
import PublicFormSettings from './pages/PublicFormSettings'
import PublicLead from './pages/PublicLead'
import AgentLogin from './pages/AgentLogin'
import AgentPortal from './pages/AgentPortal'
import Profile from './pages/Profile'
import Search from './pages/Search'
import Audit from './pages/Audit'
function Loading(){return <div className="auth-page"><div className="auth-card"><div className="auth-brand"><div>🛺</div><h1>RikshaMS</h1><span>Loading secure workspace…</span></div></div></div>}
function InternalGuard(){const {session,profile,loading}=useAuth(),loc=useLocation();if(loading)return <Loading/>;if(!session)return <Navigate to="/login" state={{from:loc.pathname+loc.search}} replace/>;if(profile?.role==='Agent')return <Navigate to="/agent" replace/>;if(!profile?.active)return <Navigate to="/login" replace/>;return <AppShell/>}
function RoleGuard({roles,children}){const {profile}=useAuth();return roles.includes(profile?.role)?children:<Navigate to="/" replace/>}
function AgentGuard(){const {session,profile,loading}=useAuth();if(loading)return <Loading/>;if(!session)return <Navigate to="/login" replace/>;if(profile?.role!=='Agent')return <Navigate to="/" replace/>;return <AgentPortal/>}
export default function App(){return <BrowserRouter><AuthProvider><Routes><Route path="/login" element={<Login/>}/><Route path="/agent-login/:token" element={<AgentLogin/>}/><Route path="/public/:token" element={<PublicLead/>}/><Route path="/agent/*" element={<AgentGuard/>}/><Route element={<InternalGuard/>}><Route path="/" element={<Dashboard/>}/><Route path="/leads" element={<Leads/>}/><Route path="/leads/:id" element={<Leads/>}/><Route path="/orders/new" element={<NewOrder/>}/><Route path="/orders" element={<Orders/>}/><Route path="/orders/:id" element={<Orders/>}/><Route path="/dispatch" element={<Dispatch/>}/><Route path="/fleet" element={<RoleGuard roles={['Admin','Manager']}><Fleet/></RoleGuard>}/> <Route path="/customers" element={<Customers/>}/><Route path="/receive-pay" element={<RoleGuard roles={['Admin','Manager']}><ReceivePay/></RoleGuard>}/> <Route path="/day-book" element={<RoleGuard roles={['Admin','Manager']}><DayBook/></RoleGuard>}/> <Route path="/slips" element={<Slips/>}/><Route path="/reports" element={<RoleGuard roles={['Admin','Manager']}><Reports/></RoleGuard>}/> <Route path="/access" element={<RoleGuard roles={['Admin','Manager']}><Access/></RoleGuard>}/> <Route path="/notices" element={<RoleGuard roles={['Admin','Manager']}><NoticeCenter/></RoleGuard>}/> <Route path="/public-form" element={<RoleGuard roles={['Admin','Manager']}><PublicFormSettings/></RoleGuard>}/> <Route path="/settings" element={<RoleGuard roles={['Admin']}><Settings/></RoleGuard>}/> <Route path="/profiles/:type/:id" element={<Profile/>}/><Route path="/search" element={<Search/>}/><Route path="/audit" element={<RoleGuard roles={['Admin','Manager']}><Audit/></RoleGuard>}/> </Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes></AuthProvider></BrowserRouter>}