import {useEffect,useMemo,useState} from 'react';
import {Navigate,NavLink,Route,Routes,useNavigate,useParams} from 'react-router-dom';
import QRCode from 'qrcode';
import {supabase} from './lib/supabase';
import {modules,nav,orderStages} from './config/modules';

const money=n=>'NPR '+Number(n||0).toLocaleString();
const fmt=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('en-NP',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kathmandu'}).format(d)};
const slug=s=>String(s||'').toLowerCase().replaceAll(' ','-');

function Modal({title,onClose,children,wide=false}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={'modal '+(wide?'wide':'')}><div className="modal-head"><h3>{title}</h3><button onClick={onClose}>×</button></div><div className="modal-body">{children}</div></div></div>}
function Field({f,value}){const common={name:f.key,defaultValue:value??'',required:['name','phone','pickup','drop','number'].includes(f.key)};if(f.type==='textarea')return <textarea {...common}/>;if(f.type==='select')return <select {...common}>{(f.options||[]).map(x=><option key={x}>{x}</option>)}</select>;return <input {...common} type={f.type||'text'}/>}

function Login({onReady}){const [pin,setPin]=useState(''),[email,setEmail]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password:pin});if(error)setError(error.message);else onReady();setBusy(false)}
 return <div className="login-shell"><form className="login-card" onSubmit={submit}><div className="brandmark">🛺</div><h1>RikshaMS</h1><p>Transport Management</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>4-digit PIN<input inputMode="numeric" pattern="\d{4}" maxLength="4" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Login'}</button></form></div>}

function Layout({profile,onLogout}){const navigate=useNavigate();const agentNav=[['dashboard','▦','Dashboard'],['leads','◎','My Leads'],['publicform','↗','Public Form'],['notices','🔔','Notices']];const visibleNav=String(profile?.role||'').toLowerCase()==='agent'?agentNav:nav;return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brandmark">🛺</div><div className="brandtext"><b>RikshaMS</b><span>Transport Management</span></div></div><nav>{visibleNav.map(([p,i,n])=><NavLink key={p} to={'/'+p} className={({isActive})=>isActive?'active':''}><span>{i}</span><em>{n}</em></NavLink>)}</nav><div className="side-card"><b>Vehicle + Labour</b><span>Booking, dispatch, rate, payment and profit in one place.</span></div></aside><main className="main"><header className="topbar"><form className="global-search" onSubmit={e=>{e.preventDefault();navigate('/orders')}}>⌕ <input placeholder="Search lead, order, customer, vehicle, labour..."/></form><div className="top-actions"><div className="avatar">{String(profile?.display_name||'A').slice(0,2).toUpperCase()}</div><div className="profile"><b>{profile?.display_name||'Administrator'}</b><span>{profile?.role||'Admin'}</span></div><button className="outline small" onClick={onLogout}>Logout</button></div></header><Routes>
 <Route index element={<Navigate to="/dashboard" replace/>}/><Route path="dashboard" element={<Dashboard/>}/><Route path="leads" element={<CrudPage config={modules.leads}/>}/><Route path="new" element={<NewOrder/>}/><Route path="orders" element={<Orders/>}/><Route path="dispatch" element={<Dispatch/>}/><Route path="fleet" element={<Fleet/>}/><Route path="customers" element={<CrudPage config={modules.customers}/>}/><Route path="slips" element={<Slips/>}/><Route path="receivepay" element={<ReceivePay/>}/><Route path="daybook" element={<DayBook/>}/><Route path="reports" element={<Reports/>}/><Route path="publicform" element={<DirectPublicForm/>}/><Route path="access" element={<Access/>}/><Route path="notices" element={<CrudPage config={modules.notices}/>}/><Route path="settings" element={<Settings/>}/></Routes><MobileNav/></main></div>}
function MobileNav(){return <div className="mobile-bottom-nav">{[['dashboard','⌂'],['leads','◎'],['new','＋'],['orders','▤'],['dispatch','➤']].map(([p,i])=><NavLink key={p} to={'/'+p}>{i}<small>{p==='new'?'Order':p}</small></NavLink>)}</div>}
function Title({title,sub,action}){return <div className="page-title"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}

function Dashboard(){const [s,setS]=useState({});const [recent,setRecent]=useState([]);useEffect(()=>{(async()=>{const qs=await Promise.all(['leads','orders','vehicles','labourers','customers','transactions'].map(t=>supabase.from(t).select('*',{count:'exact',head:true})));setS({leads:qs[0].count||0,orders:qs[1].count||0,vehicles:qs[2].count||0,labour:qs[3].count||0,customers:qs[4].count||0,tx:qs[5].count||0});const {data}=await supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(8);setRecent(data||[])})()},[]);return <div className="content"><Title title="Dashboard" sub="Live operations overview"/><div className="stats-grid seven">{[['◎','Total Leads',s.leads],['▤','Orders',s.orders],['🚚','Vehicles',s.vehicles],['👷','Labour',s.labour],['●','Customers',s.customers],['रु','Transactions',s.tx],['✓','System','Live']].map(([i,l,v])=><div className="stat-card" key={l}><div className="stat-icon">{i}</div><div><span>{l}</span><strong>{v}</strong><small>Supabase live data</small></div></div>)}</div><section className="panel"><div className="panel-head"><h3>Recent Orders</h3></div><DataTable rows={recent}/></section></div>}

function CrudPage({config}){const [rows,setRows]=useState([]),[q,setQ]=useState(''),[status,setStatus]=useState('All'),[sort,setSort]=useState('newest'),[view,setView]=useState('table'),[open,setOpen]=useState(false),[edit,setEdit]=useState(null),[err,setErr]=useState('');
 async function load(){const {data,error}=await supabase.from(config.table).select('*').order('created_at',{ascending:false});if(error)setErr(error.message);setRows(data||[])}
 useEffect(()=>{load()},[config.table]);
 const shown=useMemo(()=>{let a=rows.filter(r=>!q||config.search.some(k=>String(r[k]??'').toLowerCase().includes(q.toLowerCase())));if(status!=='All')a=a.filter(r=>String(r.status||r.active)===status);if(sort==='oldest')a=[...a].reverse();return a},[rows,q,status,sort,config]);
 async function save(e){e.preventDefault();const fd=new FormData(e.currentTarget),p={};config.fields.forEach(f=>{let v=fd.get(f.key);if(v==='')v=null;if(f.type==='number'&&v!==null)v=Number(v);p[f.key]=v});const res=edit?await supabase.from(config.table).update(p).eq('id',edit.id):await supabase.from(config.table).insert(p);if(res.error){setErr(res.error.message);return}setOpen(false);setEdit(null);load()}
 async function archive(r){if(!confirm('Archive this record?'))return;const res=await supabase.from(config.table).update({archived:true,active:false,status:r.status?'Inactive':undefined}).eq('id',r.id);if(res.error)setErr(res.error.message);else load()}
 return <div className="content"><Title title={config.title} sub="Search, filter, sort, table/card view and record management." action={<button className="primary" onClick={()=>{setEdit(null);setOpen(true)}}>＋ Add</button>}/>{err&&<div className="error">{err}</div>}<div className="filterbar advanced"><div className="searchbox">⌕ <input placeholder={'Search '+config.title} value={q} onChange={e=>setQ(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Active</option><option>Inactive</option><option>Available</option><option>Busy</option><option>New</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option></select><div className="view-toggle"><button className={view==='table'?'active':''} onClick={()=>setView('table')}>▤</button><button className={view==='card'?'active':''} onClick={()=>setView('card')}>▦</button></div></div>{view==='table'?<DataTable rows={shown} onEdit={r=>{setEdit(r);setOpen(true)}} onArchive={archive}/>:<div className="cards-grid">{shown.map(r=><article className="record-card" key={r.id}><div className="record-card-head"><div><b>{r.name||r.title||r.number||r.id}</b><small>{r.status||r.audience||''}</small></div><button className="outline small" onClick={()=>{setEdit(r);setOpen(true)}}>Edit</button></div><div className="mini-grid">{config.fields.slice(0,6).map(f=><div key={f.key}><small>{f.label}</small><b>{String(r[f.key]??'—')}</b></div>)}</div></article>)}</div>}{open&&<Modal title={(edit?'Edit ':'Add ')+config.title} onClose={()=>setOpen(false)} wide><form className="form-grid cols-2" onSubmit={save}>{config.fields.map(f=><label className="field" key={f.key}><span>{f.label}</span><Field f={f} value={edit?.[f.key]}/></label>)}<div className="modal-foot span-2"><button type="button" className="outline" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">Save</button></div></form></Modal>}</div>}

function DataTable({rows=[],onEdit,onArchive}){if(!rows.length)return <div className="empty-state"><b>No records found</b><span>Data will appear here.</span></div>;const keys=Object.keys(rows[0]).filter(k=>!['timeline','profile_notes','snapshot','quote_history','followups','labour_ids','labour_commitments'].includes(k)).slice(0,8);return <div className="table-wrap"><table><thead><tr><th>SN</th>{keys.map(k=><th key={k}>{k.replaceAll('_',' ')}</th>)}{(onEdit||onArchive)&&<th>Action</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}><td>{i+1}</td>{keys.map(k=><td key={k}>{k.includes('at')?fmt(r[k]):typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k]??'—')}</td>)}{(onEdit||onArchive)&&<td><div className="action-row">{onEdit&&<button className="outline small" onClick={()=>onEdit(r)}>Edit</button>}{onArchive&&<button className="ghost small" onClick={()=>onArchive(r)}>Archive</button>}</div></td>}</tr>)}</tbody></table></div>}

function NewOrder(){const [customers,setCustomers]=useState([]),[vehicles,setVehicles]=useState([]),[labour,setLabour]=useState([]),[message,setMessage]=useState('');useEffect(()=>{Promise.all([supabase.from('customers').select('id,name,mobile'),supabase.from('vehicles').select('id,type,number,status'),supabase.from('labourers').select('id,name,status')]).then(([c,v,l])=>{setCustomers(c.data||[]);setVehicles(v.data||[]);setLabour(l.data||[])})},[]);
 async function save(e){e.preventDefault();const fd=new FormData(e.currentTarget);const p=Object.fromEntries(fd.entries());p.id='ORD-'+Date.now().toString().slice(-8);p.status='New';p.labour_ids=fd.getAll('labour_ids');p.customer_rate=Number(p.customer_rate||0);p.vehicle_cost=Number(p.vehicle_cost||0);p.labour_cost=Number(p.labour_cost||0);p.timeline=[{stage:'New',at:new Date().toISOString()}];const {error}=await supabase.from('orders').insert(p);setMessage(error?error.message:'Order created successfully: '+p.id);if(!error)e.currentTarget.reset()}
 return <div className="content"><Title title="New Order" sub="Create a transport + labour booking using the V21 workflow."/><div className="new-order-layout"><form className="form-stack" onSubmit={save}><section className="panel form-section"><h3>Customer & Route</h3><div className="form-grid cols-2"><label className="field"><span>Customer</span><select name="customer_id"><option value="">Walk-in / New</option>{customers.map(x=><option value={x.id} key={x.id}>{x.name} · {x.mobile}</option>)}</select></label><label className="field"><span>Customer Name</span><input name="customer" required/></label><label className="field"><span>Phone</span><input name="phone" required/></label><label className="field"><span>Pickup</span><input name="pickup" required/></label><label className="field"><span>Drop</span><input name="drop" required/></label><label className="field"><span>Goods</span><input name="goods"/></label><label className="field"><span>Date</span><input name="date" type="date"/></label><label className="field"><span>Time</span><input name="time" type="time"/></label></div></section><section className="panel form-section"><h3>Vehicle & Labour</h3><div className="form-grid cols-2"><label className="field"><span>Vehicle</span><select name="vehicle_id"><option value="">Assign later</option>{vehicles.map(x=><option value={x.id} key={x.id}>{x.number} · {x.type} · {x.status}</option>)}</select></label><label className="field"><span>Vehicle Type</span><input name="vehicle_type"/></label><label className="field span-2"><span>Labour</span><select name="labour_ids" multiple size="5">{labour.map(x=><option value={x.id} key={x.id}>{x.name} · {x.status}</option>)}</select></label></div></section><section className="panel form-section"><h3>Pricing</h3><div className="form-grid cols-3"><label className="field"><span>Customer Rate</span><input name="customer_rate" type="number"/></label><label className="field"><span>Vehicle Cost</span><input name="vehicle_cost" type="number"/></label><label className="field"><span>Labour Cost</span><input name="labour_cost" type="number"/></label></div></section>{message&&<div className="settings-note">{message}</div>}<button className="primary full">Create Order</button></form><aside className="order-summary"><small className="live-preview-kicker">V21 ORDER</small><h3>Order Summary</h3><p>New → Quoted → Assigned → Dispatched → In Transit → Delivered → Completed</p></aside></div></div>}

function Orders(){const [rows,setRows]=useState([]),[q,setQ]=useState('');async function load(){const {data}=await supabase.from('orders').select('*').order('created_at',{ascending:false});setRows(data||[])}useEffect(()=>{load()},[]);
 async function move(r,next){const field={Assigned:'assigned_at',Dispatched:'dispatched_at','In Transit':'trip_started_at',Delivered:'delivered_at',Completed:'completed_at',Cancelled:'cancelled_at'}[next];const tl=[...(r.timeline||[]),{stage:next,at:new Date().toISOString()}];const p={status:next,last_stage_at:new Date().toISOString(),timeline:tl};if(field)p[field]=new Date().toISOString();await supabase.from('orders').update(p).eq('id',r.id);load()}
 const shown=rows.filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q.toLowerCase()));return <div className="content"><Title title="Orders" sub="Stage-controlled order workflow."/><div className="filterbar"><div className="searchbox">⌕ <input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search order, customer, route..."/></div></div><div className="table-wrap orders-table"><table><thead><tr><th>Order</th><th>Customer</th><th>Route</th><th>Vehicle</th><th>Status</th><th>Payment</th><th>Rate</th><th>Action</th></tr></thead><tbody>{shown.map(r=>{const i=orderStages.indexOf(r.status);const next=i>=0&&i<6?orderStages[i+1]:null;return <tr key={r.id}><td><b>{r.id}</b><small>{fmt(r.created_at)}</small></td><td>{r.customer}<small>{r.phone}</small></td><td>{r.pickup} → {r.drop}</td><td>{r.vehicle_type||'—'}</td><td><span className={'badge '+slug(r.status)}>{r.status}</span></td><td>{r.payment||'Pending'}</td><td>{money(r.customer_rate)}</td><td><div className="action-row">{next&&<button className="primary small" onClick={()=>move(r,next)}>{next}</button>}{!['Completed','Cancelled'].includes(r.status)&&<button className="outline small" onClick={()=>move(r,'Cancelled')}>Cancel</button>}</div></td></tr>})}</tbody></table></div></div>}

function Dispatch(){const [orders,setOrders]=useState([]),[vehicles,setVehicles]=useState([]),[drivers,setDrivers]=useState([]),[labour,setLabour]=useState([]),[pick,setPick]=useState(null);async function load(){const [o,v,d,l]=await Promise.all([supabase.from('orders').select('*').in('status',['Quoted','Assigned','Dispatched']),supabase.from('vehicles').select('*').eq('status','Available'),supabase.from('drivers').select('*').eq('status','Available'),supabase.from('labourers').select('*').eq('status','Available')]);setOrders(o.data||[]);setVehicles(v.data||[]);setDrivers(d.data||[]);setLabour(l.data||[])}useEffect(()=>{load()},[]);
 async function assign(e){e.preventDefault();const fd=new FormData(e.currentTarget);const p={vehicle_id:fd.get('vehicle_id'),driver_id:fd.get('driver_id'),labour_ids:fd.getAll('labour_ids'),status:'Dispatched',dispatched_at:new Date().toISOString(),last_stage_at:new Date().toISOString(),timeline:[...(pick.timeline||[]),{stage:'Dispatched',at:new Date().toISOString()}]};await supabase.from('orders').update(p).eq('id',pick.id);if(p.vehicle_id)await supabase.from('vehicles').update({status:'Busy'}).eq('id',p.vehicle_id);if(p.driver_id)await supabase.from('drivers').update({status:'Busy'}).eq('id',p.driver_id);if(p.labour_ids.length)await supabase.from('labourers').update({status:'Busy'}).in('id',p.labour_ids);setPick(null);load()}
 return <div className="content"><Title title="Dispatch" sub="All eligible orders appear in the dispatch queue."/><div className="cards-grid">{orders.map(o=><article className="record-card dispatch-queue-card ready" key={o.id}><div className="record-card-head"><div><b>{o.id}</b><small>{o.customer}</small></div><span className={'badge '+slug(o.status)}>{o.status}</span></div><div className="route-line"><span>{o.pickup}</span>→<span>{o.drop}</span></div><button className="primary full" onClick={()=>setPick(o)}>Assign / Dispatch</button></article>)}</div>{pick&&<Modal title={'Dispatch '+pick.id} onClose={()=>setPick(null)} wide><form className="form-grid cols-2" onSubmit={assign}><label className="field"><span>Vehicle</span><select name="vehicle_id" required><option value="">Select</option>{vehicles.map(x=><option value={x.id} key={x.id}>{x.number} · {x.type}</option>)}</select></label><label className="field"><span>Driver</span><select name="driver_id"><option value="">Select</option>{drivers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="field span-2"><span>Labour</span><select name="labour_ids" multiple size="6">{labour.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><div className="modal-foot span-2"><button className="primary">Assign & Dispatch</button></div></form></Modal>}</div>}

function Fleet(){const [tab,setTab]=useState('vehicles');const c=tab==='vehicles'?modules.vehicles:tab==='labour'?modules.labour:tab==='drivers'?modules.drivers:tab==='owners'?modules.vehicleOwners:modules.partners;return <div><div className="content"><Title title="Fleet & Crew" sub="Vehicles, drivers, labour, owners and partners."/><div className="status-tabs">{[['vehicles','Vehicles'],['drivers','Drivers'],['labour','Labour'],['owners','Owners'],['partners','Partners']].map(([k,n])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{n}</button>)}</div></div><CrudPage config={c}/></div>}

function ReceivePay(){const [rows,setRows]=useState([]),[open,setOpen]=useState(false),[direction,setDirection]=useState('Receive');async function load(){const {data}=await supabase.from('transactions').select('*').order('created_at',{ascending:false});setRows(data||[])}useEffect(()=>{load()},[]);async function save(e){e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget).entries());p.id='TX-'+Date.now().toString().slice(-8);p.direction=direction;p.amount=Number(p.amount);p.status='Posted';await supabase.from('transactions').insert(p);setOpen(false);load()}return <div className="content"><Title title="Receive & Pay" sub="Customer receipts, vehicle/driver/labour/partner payments and expenses." action={<div className="action-row"><button className="primary" onClick={()=>{setDirection('Receive');setOpen(true)}}>Receive</button><button className="outline" onClick={()=>{setDirection('Pay');setOpen(true)}}>Pay</button></div>}/><DataTable rows={rows}/>{open&&<Modal title={direction} onClose={()=>setOpen(false)}><form className="form-grid cols-2" onSubmit={save}><label className="field"><span>Order ID</span><input name="order_id"/></label><label className="field"><span>Party Type</span><select name="party_type"><option>Customer</option><option>Vehicle Owner</option><option>Driver</option><option>Labour</option><option>Partner</option><option>Expense</option></select></label><label className="field"><span>Party Name</span><input name="party_name"/></label><label className="field"><span>Type</span><input name="type"/></label><label className="field"><span>Amount</span><input name="amount" type="number" required/></label><label className="field"><span>Method</span><select name="method"><option>Cash</option><option>Bank</option><option>eSewa</option><option>Khalti</option><option>Credit</option></select></label><label className="field span-2"><span>Note</span><textarea name="note"/></label><div className="modal-foot span-2"><button className="primary">Save Transaction</button></div></form></Modal>}</div>}

function DayBook(){const [rows,setRows]=useState([]),[range,setRange]=useState('daily');useEffect(()=>{supabase.from('transactions').select('*').order('created_at',{ascending:false}).then(x=>setRows(x.data||[]))},[]);const filtered=useMemo(()=>{const n=new Date();let s=new Date(0);if(range==='daily')s=new Date(n.getFullYear(),n.getMonth(),n.getDate());if(range==='weekly')s=new Date(n.getTime()-7*864e5);if(range==='monthly')s=new Date(n.getFullYear(),n.getMonth(),1);return rows.filter(x=>new Date(x.created_at)>=s)},[rows,range]);return <div className="content"><Title title="Day Book" sub="Daily, weekly, monthly and all transaction view."/><div className="filterbar"><select value={range} onChange={e=>setRange(e.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="all">All</option></select></div><DataTable rows={filtered}/></div>}

function Reports(){const [orders,setOrders]=useState([]),[tx,setTx]=useState([]);useEffect(()=>{Promise.all([supabase.from('orders').select('*'),supabase.from('transactions').select('*')]).then(([o,t])=>{setOrders(o.data||[]);setTx(t.data||[])})},[]);const revenue=tx.filter(x=>x.direction==='Receive').reduce((a,b)=>a+Number(b.amount||0),0),pay=tx.filter(x=>x.direction==='Pay').reduce((a,b)=>a+Number(b.amount||0),0);return <div className="content report-page"><Title title="Accounts & Reports" sub="Operations, revenue, expense, margin and settlement summary."/><div className="report-stats stats-grid four"><div className="stat-card"><div><span>Revenue</span><strong>{money(revenue)}</strong></div></div><div className="stat-card"><div><span>Payments</span><strong>{money(pay)}</strong></div></div><div className="stat-card"><div><span>Margin</span><strong>{money(revenue-pay)}</strong></div></div><div className="stat-card"><div><span>Orders</span><strong>{orders.length}</strong></div></div></div><div className="grid-2"><section className="panel"><h3>Orders by status</h3>{orderStages.map(s=><div className="money-row" key={s}><span>{s}</span><b>{orders.filter(o=>o.status===s).length}</b></div>)}</section><section className="panel"><h3>Transaction Summary</h3><DataTable rows={tx.slice(0,12)}/></section></div></div>}

function Slips(){const [orders,setOrders]=useState([]);useEffect(()=>{supabase.from('orders').select('*').order('created_at',{ascending:false}).then(x=>setOrders(x.data||[]))},[]);async function slip(o,type){const slipNo=type.toUpperCase()+'-'+Date.now().toString().slice(-8);const snap={order:o};await supabase.from('slips').upsert({id:slipNo,slip_no:slipNo,type,order_id:o.id,customer_name:o.customer,customer_phone:o.phone,amount:o.customer_rate,snapshot:snap,status:'Active'},{onConflict:'slip_no'});const w=window.open('','_blank');w.document.write('<html><head><title>'+slipNo+'</title><style>body{font-family:Arial;padding:40px}.r{display:flex;justify-content:space-between;padding:8px;border-bottom:1px solid #ddd}</style></head><body><h1>RikshaMS</h1><p>'+type+' · '+slipNo+'</p><div class=r><b>Order</b><span>'+o.id+'</span></div><div class=r><b>Customer</b><span>'+o.customer+'</span></div><div class=r><b>Route</b><span>'+o.pickup+' → '+o.drop+'</span></div><div class=r><b>Amount</b><span>'+money(o.customer_rate)+'</span></div><br><button onclick=window.print()>Print</button></body></html>');w.document.close()}return <div className="content"><Title title="Slips" sub="Order Slip, Dispatch Slip and Receipt."/><div className="cards-grid">{orders.map(o=><article className="record-card" key={o.id}><b>{o.id}</b><p>{o.customer}</p><div className="action-row"><button className="outline small" onClick={()=>slip(o,'Order Slip')}>Order Slip</button><button className="outline small" onClick={()=>slip(o,'Dispatch Slip')}>Dispatch Slip</button><button className="outline small" onClick={()=>slip(o,'Receipt')}>Receipt</button></div></article>)}</div></div>}

function DirectPublicForm(){const [row,setRow]=useState(null),[qr,setQr]=useState('');useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();let profile=null;if(session){const p=await supabase.from('profiles').select('id,role').eq('auth_user_id',session.user.id).maybeSingle();profile=p.data}let q=supabase.from('public_forms').select('*');q=String(profile?.role||'').toLowerCase()==='agent'?q.eq('owner_profile_id',profile.id):q.eq('owner_type','Admin');const x=await q.maybeSingle();setRow(x.data);if(x.data?.token)setQr(await QRCode.toDataURL(location.origin+'/public/'+x.data.token))})()},[]);return <div className="content"><Title title="Direct Public Form" sub="Admin-owned public enquiry link and QR."/><section className="panel">{row?<><div className="detail-grid"><div><small>Title</small><b>{row.title}</b></div><div><small>Status</small><b>{row.active?'Live':'Off'}</b></div><div><small>Public URL</small><b>{location.origin+'/public/'+row.token}</b></div></div>{qr&&<img src={qr} alt="Public QR" style={{width:180,marginTop:16}}/>}</>:<p>No direct public form yet. Create one from Supabase seed/setup SQL.</p>}</section></div>}

function Access(){const [rows,setRows]=useState([]),[open,setOpen]=useState(false),[qr,setQr]=useState('');async function load(){const {data}=await supabase.from('profiles').select('*').order('created_at',{ascending:false});setRows(data||[])}useEffect(()=>{load()},[]);async function save(e){e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget).entries());p.login_token=p.login_token||crypto.randomUUID().slice(0,8).toUpperCase();const {data,error}=await supabase.functions.invoke('manage-access',{body:p});if(error||!data?.success){alert(data?.message||error?.message||'Could not create access');return}setOpen(false);load()}async function showQr(r){setQr(await QRCode.toDataURL(location.origin+'/agent-login/'+r.login_token))}return <div className="content"><Title title="User / Agent Access" sub="Operational profiles, login token, role, QR and active status." action={<button className="primary" onClick={()=>setOpen(true)}>＋ Add User</button>}/><DataTable rows={rows}/><div className="cards-grid mt">{rows.map(r=><article className="record-card" key={r.id}><b>{r.display_name}</b><small>{r.role}</small><div className="action-row"><button className="outline small" onClick={()=>showQr(r)}>QR</button></div></article>)}</div>{qr&&<Modal title="Login QR" onClose={()=>setQr('')}><img src={qr} alt="Login QR" style={{width:260,display:'block',margin:'20px auto'}}/></Modal>}{open&&<Modal title="Add User / Agent" onClose={()=>setOpen(false)}><form className="form-grid cols-2" onSubmit={save}><label className="field"><span>Display Name</span><input name="display_name" required/></label><label className="field"><span>Profile Type</span><input name="profile_type" defaultValue="Agent"/></label><label className="field"><span>Role</span><select name="role"><option>Agent</option><option>Staff</option><option>Manager</option><option>Admin</option></select></label><label className="field"><span>Mobile</span><input name="mobile"/></label><label className="field"><span>Login Token</span><input name="login_token"/></label><label className="field"><span>4-digit PIN</span><input name="pin" inputMode="numeric" pattern="\\d{4}" maxLength="4" required/></label><div className="modal-foot span-2"><button className="primary">Save</button></div></form></Modal>}</div>}

function Settings(){return <div className="content"><Title title="Admin Settings" sub="System configuration for the React + Supabase version."/><div className="settings-grid"><section className="panel"><h3>Backend</h3><div className="settings-note">Supabase PostgreSQL + Auth + RLS + Realtime replace Google Apps Script and Sheets.</div></section><section className="panel"><h3>Security</h3><div className="settings-note">Authentication uses Supabase Auth; permissions are enforced by Row Level Security, not only UI hiding.</div></section><section className="panel"><h3>Pricing</h3><div className="settings-note">Rates are stored in the rates table and used by order pricing.</div></section><section className="panel"><h3>Timezone</h3><div className="settings-note">Display timezone: Asia/Kathmandu. PostgreSQL stores timestamptz consistently.</div></section></div></div>}

function PublicLead(){const {token}=useParams();const [form,setForm]=useState(null),[done,setDone]=useState(''),[err,setErr]=useState('');useEffect(()=>{supabase.from('public_forms').select('*,profiles(display_name)').eq('token',token).eq('active',true).maybeSingle().then(x=>setForm(x.data))},[token]);async function submit(e){e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget).entries());p.id='LEAD-'+Date.now().toString().slice(-8);p.source=form?.owner_type==='Admin'?'Direct Public Form':'Agent Referral';p.created_by_profile_id=form?.owner_profile_id||null;p.status='New';const {error}=await supabase.from('leads').insert(p);if(error)setErr(error.message);else setDone(p.id)}if(!form)return <div className="public-lead-shell"><div className="public-lead-card">Loading form…</div></div>;if(done)return <div className="public-lead-shell"><div className="public-lead-card public-success"><h2>Enquiry Submitted</h2><p>Lead ID: {done}</p></div></div>;return <div className="public-lead-shell"><form className="public-lead-card" onSubmit={submit}><div className="public-lead-brand"><span>🛺</span><div><h2>{form.title||'Transport Enquiry'}</h2><small>{form.owner_type==='Admin'?'Direct enquiry form':'Referred by '+(form.profiles?.display_name||'Transport Partner')}</small></div></div><div className="modern-form-grid"><label className="field"><span>Full Name *</span><input name="name" required/></label><label className="field"><span>Phone *</span><input name="phone" required/></label><label className="field"><span>Pickup *</span><input name="pickup" required/></label><label className="field"><span>Drop *</span><input name="drop" required/></label><label className="field"><span>Goods</span><input name="goods"/></label><label className="field"><span>Vehicle Type</span><input name="vehicle_type" defaultValue="Not decided"/></label></div>{err&&<div className="error">{err}</div>}<button className="primary full">Submit Enquiry</button></form></div>}

function AgentLogin(){const {loginToken}=useParams();const [pin,setPin]=useState(''),[err,setErr]=useState(''),navg=useNavigate();async function submit(e){e.preventDefault();setErr('');const email=String(loginToken||'').toLowerCase()+'@rikshams.local';const {error}=await supabase.auth.signInWithPassword({email,password:pin});if(error)setErr(error.message);else navg('/dashboard',{replace:true})}return <div className="login-shell"><form className="login-card" onSubmit={submit}><div className="brandmark">🛺</div><h1>RikshaMS</h1><p>Agent Login · {loginToken}</p><label>4-digit PIN<input inputMode="numeric" pattern="\\d{4}" maxLength="4" value={pin} onChange={e=>setPin(e.target.value.replace(/\\D/g,'').slice(0,4))} required/></label>{err&&<div className="error">{err}</div>}<button className="primary">Login</button></form></div>}

export default function App(){const [session,setSession]=useState(undefined),[profile,setProfile]=useState(null);async function loadProfile(s){if(!s){setProfile(null);return}const {data}=await supabase.from('profiles').select('*').eq('auth_user_id',s.user.id).maybeSingle();setProfile(data)}useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);loadProfile(data.session)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);loadProfile(s)});return()=>data.subscription.unsubscribe()},[]);if(session===undefined)return <div className="loading">Loading RikshaMS…</div>;return <Routes><Route path="/public/:token" element={<PublicLead/>}/><Route path="/agent-login/:loginToken" element={<AgentLogin/>}/><Route path="/*" element={session?<Layout profile={profile} onLogout={()=>supabase.auth.signOut()}/>:<Login onReady={()=>{}}/>}/></Routes>}